### PR TITLE
fix: remove the parameter number limit for functionType infer

### PR DESCRIPTION
**Pull request by HerrCai0907**
fix error report of code:
```typescript
function foo<T>(fn: () => T): void {
  trace(nameof<T>());
}
foo((): string => ""); // Type argument expected.
```

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by dcodeIO** [comment]
Can you explain in a few sentences what this change does exactly? I'm probably just missing it, but I'm not quite seeing which limit was removed.

**Comment by HerrCai0907** [comment]
@dcodeIO limit is `parameterNodes && parameterNodes.length > 0`. But actually function can receive a callback which parameter count less than signature parameter count. So this limit can be removed.

**Review by dcodeIO — APPROVED** [review]

**Comment by MaxGraey** [comment]
Please resolve fixture's conflict

**Comment by MaxGraey** [comment]
Thanks!

**Pull request merged**
