### PR TITLE
sync AS and portable behaviour for Array#sort with default comparator

### PR DESCRIPTION
**Pull request by MaxGraey**
This normalize `Array#sort()` for portable so now:
```ts
[0, -0, -1, NaN, Infinity, 2, 123].sort()
```
output (which the same as AS):
```ts
[ -1, -0, 0, 2, 123, Infinity, NaN ]
```
instead:
```ts
[ -1, 0, -0, 123, 2, Infinity, NaN ]
```

This also [speed-up](https://esbench.com/bench/5d9251b84cd7e6009ef627ef) array's sort

### CODE REVIEW

**Comment by dcodeIO** [comment]
Does this work for arrays of strings?

**Comment by MaxGraey** [comment]
> Does this work for arrays of strings?
yes

**Comment by MaxGraey** [comment]
Also with [latest version](https://esbench.com/bench/5d9251b84cd7e6009ef627ef) I got pretty cheap overhead:
bench

**Comment by MaxGraey** [comment]
ok it seems I'm happy with this solution.
@dcodeIO try test this with different types. And if it will be ok it could be merged I guess

**Pull request merged**
