### PR TITLE
Refactor typedarray

### PR DESCRIPTION
**Pull request by MaxGraey**
Move typedarray's macros to util folder for better reusage.

Relate https://github.com/AssemblyScript/node/pull/20#issuecomment-517334935

### CODE REVIEW

**Comment by dcodeIO** [comment]
Hmm, making these reusable seems to add more code (as of text) to stdlib for something that the related PR can solve with just a couple lines. Not sure if worth it, considering that these things become inlined anyway. Or will there be more Buffer methods that will benefit from it?

**Comment by MaxGraey** [comment]
This provides more reusable code for Buffer in the future or any other similar class. I know NEAR use some custom containers and The Graph.

**Comment by jtenner** [comment]
I like this. Might make the `Buffer` class smaller in the node project too. 

I suggest documenting each one in the types file too. May I do that?

**Comment by dcodeIO** [comment]
Ok, let's do it then :)

**Comment by jtenner** [comment]
The only problem I see is that libraries could couple themselves to these internal functions. (as `node` will).

We shouldn't drop support for the functions they are going to be exported and used in the std node library. As long as these functions are going to stick around, I'm okay with this pull request.

**Comment by jtenner** [comment]
Is there a schedule for reviewing? I don't know if there's something wrong with my pull requests or I can move on and start working on other things.

**Pull request closed without merging**
