### PR TITLE
Add built-in indexof/valueof types

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR investigates a special type `valueof<T>` that obtains the value type of an array, a set, a map or a class with an indexed get overload (like typed arrays).

Might help to implement things like https://github.com/AssemblyScript/assemblyscript/pull/516 but the implementation is actually a bit short-sighted. TypeScript supports resolving types of the form `T[0]` for example, that does exactly this, but the resolver isn't yet powerful enough to support this (resolving of any expression etc.). So I guess the question is: Does it make sense to add this now, and once the resolver has been reworked, simply keep supporting it for backwards compatibility?

### CODE REVIEW

**Comment by MaxGraey** [comment]
Nice. What about `keyof`?
Btw idiomatic way to retrieve value in TS:
```ts
type ValueOf<T> = T[keyof T];
```

**Comment by dcodeIO** [comment]
That's what I meant with a bit short-sighted. A proper implementation would first need a new type node kind `keyof Something`, then a new type node kind `T[Something]` and finally the resolver must be able to resolve that. Not a 100% sure, but since the resolver requires a rework anyway (resolve any expression etc.), it looks like doing this properly would depend on doing that first.

**Comment by MaxGraey** [comment]
I see. So as intermediate solution this definitely make sense

**Comment by jtenner** [comment]
Count me in! This enables many great comparison patterns for my testing software.

**Comment by dcodeIO** [comment]
Thinking about this a little more, I figured that having our own special types might actually better represent what these actually do, because in TS, `keyof` doesn't just get the indexed access key, but all possible keys

```ts
type TheType = keyof Array<i32>; // number | "length" | "fill" ...
```

which is most likely nothing we'd support anytime soon anyway. Now, sadly, `keyof` is a keyword and we can't have a `keyof<T>` type, but we could just name ours `indexof<T>` obtaining the index type and `valueof<T>` obtaining the value type of indexed access. Wdyt?

**Comment by jtenner** [comment]
It would be awesome to have a type declaration statement in the function body.

```
type Child = indexof<T>; // etc. 
```

Just my 2 cents. At first glance, I think this might cause problems with the resolver. I would be grateful even if that wasn't the case.

**Comment by dcodeIO** [comment]
This now adds indexed access overloads for Map and Set to unify/simplify the concept by binding it to `[]` overloads specifically, and introduces the corresponding `indexof<T>` type.

**Comment by dcodeIO** [comment]
Docs: https://docs.assemblyscript.org/basics/types#macro-types

**Pull request merged**
