### PR TITLE
Add resolve-propertyaccess test

### PR DESCRIPTION
**Pull request by dcodeIO**
I recently noticed that there's something missing when resolving property accesses, so I added a test and found an issue with enum values. However, I think this still doesn't catch the issue I noticed initially which had something to do with resolving `i32.MAX_VALUE` somewhere. Going to investigate further.

### CODE REVIEW

**Comment by MaxGraey** [comment]
Could you also fix [this minor issue](https://github.com/AssemblyScript/assemblyscript/issues/575) for namespace?

**Comment by dcodeIO** [comment]
I think I found the initial issue, which happened for `@lazy` globals. Going to look into the other one :)

**Comment by MaxGraey** [comment]
Hmm, but in that issue I don't use @lazy globals

**Comment by dcodeIO** [comment]
Yeah, seems to be a different issue related to `ctxElement` being the start function in this case, not the namespace.

**Pull request merged**
