### PR TITLE
Add twitter badge

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Do you know if shields.io has become more reliable meanwhile? Last time I checked their badges 404ed all over the place.

**Comment by MaxGraey** [comment]
I think they are fixed all issues for now. But let me check other solutions

**Comment by MaxGraey** [comment]
How about this?

[Twitter Follow](https://twitter.com/AssemblyScript)

**Comment by dcodeIO** [comment]
As an alterantive we can always make our own little badge and host it on github pages or something. Wouldn't have a count, ofc.

**Pull request closed without merging**
