### PR TITLE
Split get typed array methods in loader to safe and unsafe (view)

### PR DESCRIPTION
**Pull request by MaxGraey**
Using `__getUint8Array` and other method lead to confusion because it require imeddiate usage of results before other allocs or deallocs. Overwise memory buffer will outdated and point to non-relevant data. Like:
```ts
const arrPtr = wasm.__allocArray(...);

const outPtr = wasm.callSomeMethod(arrPtr);
wasm.__release(outPtr);
return wasm.__getUint8Array(outPtr); // but this already outdated after `__release`

// or

const outPtr = wasm.callSomeMethod(arrPtr);
const ret = wasm.__getUint8Array(outPtr);
wasm.__release(outPtr);
return ret; // still outdated after `__release`
```
This PR make `__getUint8Array` and other methods safe by default by cloning and add new methods like `__getUint8ArrayView` which preserve previous dangers behaviour (without cloning)

### CODE REVIEW

**Comment by dcodeIO** [comment]
The intended use here is something like

```ts
const arrPtr = wasm.__retain(wasm.__allocArray(...));
const outPtr = wasm.callSomeMethod(arrPtr);
const ret = wasm.__getUint8Array(outPtr);
wasm.__release(arrPtr);
return ret;
```

with `outPtr` expected to be released on the JS side once not needed anymore (after the return), so it can keep its references (potentially including `arrPtr`) alive until then.

Also iirc, the `__getXXArray` are merely special cases of `__getArrayView` which are all intended for minimal overhead instead of safety?

**Comment by MaxGraey** [comment]
```ts
const arrPtr = wasm.__retain(wasm.__allocArray(...));
const outPtr = wasm.callSomeMethod(arrPtr);
const ret = wasm.__getUint8Array(outPtr);
wasm.__release(arrPtr);
return ret;
```
This produce the same result) `__getUint8Array` just create slice to buffer in memory which mutate after `wasm.__release`

**Comment by dcodeIO** [comment]
In the case that `outPtr` directly or indirectly retains a reference to `arrPtr`, this is what I'd expect:

```ts
const arrPtr = wasm.__retain(wasm.__allocArray(...)); // RC(arrPtr)=1
const outPtr = wasm.callSomeMethod(arrPtr); // RC(outPtr)=1 due to return, RC(arrPtr)=2
const ret = wasm.__getUint8Array(outPtr);
wasm.__release(arrPtr); // RC(arrPtr=1)
return ret;

// later

__release(outPtr); // RC(outPtr)=0, releasing its refs, then RC(arrPtr)=0
```

This is not so much about what method is called with `outPtr`, but `outPtr` being a return value of a function that is pre-retained for the caller to release, here JS. Unless `outPtr` is manually released, it should remain alive, incl. all the stuff it references. Or am I missing something?

**Comment by MaxGraey** [comment]
This not works and required `slice`. See this for example:
https://github.com/ChainSafe/as-sha256/blob/master/src/index.js#L53

Also @torch2424 come across to similar problem as I know

**Comment by dcodeIO** [comment]
The example you linked doesn't work (in the modified form below) because

```ts
  const digestPointer = wasm.digest();
  const digest = wasm.__getUint8Array(digestPointer)/* .slice() */;
  wasm.__release(digestPointer);
  return digest;
```

prematurely releases the reference while `digest` is still being used. This looks more like invalid use.

**Comment by MaxGraey** [comment]
https://github.com/ChainSafe/as-sha256/pull/23#discussion_r355427176

**Comment by dcodeIO** [comment]
Perhaps it would make sense to have two different API methods there

* **__getXXArrayView** with the current behavior, matching how **__getArrayView** works, and
* **__getXXArray** which slices, matching how **__getArray** works

Perhaps it's just confusing naming the way it is?

**Comment by MaxGraey** [comment]
Yeah, I agree with naming. Will rename `__getXXArrayUnsafe` to `__getXXArrayView`

**Comment by dcodeIO** [comment]
Also note that if such a function copies by default, we lose mutability in both ways. Without copying, one can see changes and make changes, while with copying it's rather a readonly snapshot.

**Comment by dcodeIO** [comment]
Speaking of naming, I also like the term `unsafe` in there to make this more clear. Or perhaps we can do something like **getArrayCopy** vs **getArrayView**. Hmm... instead of `View`, what's a good pre- or postfix for something that's observable, live, mutable?

**Comment by MaxGraey** [comment]
I prefer leave `__getXXArray` as is, similar to `__getArray`, `__getString` which also use copies. Also renaming `__getXXArray` to `__getXXArrayCopy` broke backward compatibility.

**Comment by dcodeIO** [comment]
Would say we are breaking backwards compatibility anyway for everyone using the existing API to modify data in either way, since `__getUint8Array` etc. now copies but didn't before. Just suggesting that if we would rename something, then we should do it now :)

**Comment by MaxGraey** [comment]
I see. But still think it better leave "as is". Btw comment notation emphasise that `__getXXArray` actually [copy the data](https://github.com/AssemblyScript/assemblyscript/pull/1047/files#diff-80632dc5a65081291fc4a0f8dcec4d78R34) and I guess it's enough.

**Comment by MaxGraey** [comment]
latest commit change cloning approach which twice faster on Google Chrome but not has similar performance on FF.

cloning

**Pull request merged**
