### PR TITLE
Fix falsy positive isInteger<bool>(x)

### LINKED ISSUE #782: isInteger<boolean>() returns true.
Here is a simple example of the issue: https://webassembly.studio/?f=nv5owy8ws4

If I have the following:

```ts
function isBool<T>(): boolean {
  if (isInteger<T>()){
    return false;
  }
  return isBoolean<T>();
}
```

Then `isBool<boolean>()` returns `false`.  I found this the hard way when checking types.  For now I always check `isBoolean<T>()` first.

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix #782

### CODE REVIEW

**Comment by jtenner** [comment]
If this is a bug, it should probably be fixed in `types.ts`

```ts
  /** A 1-bit unsigned integer. */
  static readonly bool: Type = new Type(TypeKind.BOOL,
    TypeFlags.UNSIGNED |
    TypeFlags.SHORT    |
    TypeFlags.INTEGER  |
    TypeFlags.VALUE,   1
  );
```

Since the type is literally backed by an integer, I think `isInteger<bool>()` returns correctly.

**Comment by MaxGraey** [comment]
`bool` is kind of integer with size equal `1`. But typescript separate `number` and `boolean`. Also semantically we have `isFloat` but not `isDouble` for example, in the same time we have `isInteger` and `isBoolean` that's mean they are orthogonal builtins which shouldn't be subset. It's my thoughts.

@dcodeIO wdyt?

**Comment by dcodeIO** [comment]
Status quo is based on the fact that, from a Wasm perspective, a bool is an i32, and anything that is either an i32 or i64 and not a reference `isInteger<T>`. Similarly, anything that is either an f32 or f64 (and not a reference) `isFloat<T>`.

Internally dealing with a bool like an integer makes sense in situations where it is loaded or stored, since that uses i32 instructions.

My concern here is that the `isInteger`, `isFloat` etc. built-ins reflect the compiler's static knowledge of the types, and the compiler considers bools integers. So, changing that makes the built-in not exactly reflect the compiler. Considering that `isInteger` itself isn't a TS but more an AS thing, that doesn't seem quite right.

**Comment by MaxGraey** [comment]
It's just that if you stick to the semantics of JavaScript, then Number and Boolean are two different types
```ts
typeof true
> "boolean"
typeof 1
> "number"
```

**Comment by jtenner** [comment]
I'm all for implementing a proper typeof expression.

**Comment by MaxGraey** [comment]
@jtenner It will be great!

**Pull request closed without merging**
