### PR TITLE
Throw unimplemented error when using spread operator

### LINKED ISSUE #1853: Meet error about `...` operator
mini example: 
```ts
class Foo {
    data(): Array<u8> {
        return [];
    }
}
export class Bar extends Foo {
    data(): Array<u8> {
        return [...super.data()];
    }
}
```

The error:
```
▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is a stack trace that may or may not be useful:
▌ 
▌ AssertionError: assertion failed
▌     at i.assert (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:737243)
▌     at f.compileUnaryPrefixExpression (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:331940)
▌     at f.compileExpression (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:238684)
▌     at f.compileArrayLiteral (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:310195)
▌     at f.compileLiteralExpression (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:306265)
▌     at f.compileExpression (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:238319)
▌     at f.compileReturnStatement (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:230012)
▌     at f.compileStatement (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:223143)
▌     at f.compileStatements (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:223935)
▌     at f.compileFunctionBody (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:213143)
▌ 
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

### PR DESCRIPTION
**Pull request by romdotdog**
I'm not exactly sure what the current status of the spread operator is, but I noticed that the compiler crashes when using it
fixes #1853
all tests passed in my fork

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by MaxGraey** [comment]
Could you add your name & email in [NOTICE](https://github.com/AssemblyScript/assemblyscript/blob/main/NOTICE#L41)?

**Comment by romdotdog** [comment]
Done!

**Review by dcodeIO — APPROVED** [review]

**Comment by MaxGraey** [comment]
@romdotdog plz resync with master

**Comment by romdotdog** [comment]
@MaxGraey @dcodeIO Finished

**Comment by MaxGraey** [comment]
@dcodeIO Hmm, why it add extra `70765447`?
```
Author '70765447+romdotdog@users.noreply.github.com' does not appear to be listed in the NOTICE file, yet.
```

**Comment by dcodeIO** [comment]
Seems like that's just the format these email addresses take. There is another one further above having a prefix.

**Comment by MaxGraey** [comment]
Did you try `AUTHOR=$(git log -1 --format="%ae" HASH^!)` instead `--format="%aE"`?

**Comment by dcodeIO** [comment]
We don't use mailmap, so doesn't seem related.

**Comment by dcodeIO** [comment]
Btw, afaik the main part of the email is `70765447@`, with the `+something` typically rather a tag. Not 100% what GH uses, ofc, but looks like they prefer a unique ID. Perhaps the name can change?

**Comment by MaxGraey** [comment]
> We don't use mailmap, so doesn't seem related.

But current `%aE` relate to mailmap

**Comment by romdotdog** [comment]
> Btw, afaik the main part of the email is `70765447@`, with the `+something` typically rather a tag. Not 100% sure what GH uses, ofc, but looks like they prefer a unique ID. Perhaps the name can change?

This definitely makes sense. I just did `git config --global user.email` into my console and copied it 😅

**Comment by MaxGraey** [comment]
Thanks!

**Pull request merged**
