### PR TITLE
Optimize some std mem methods by replacing expensive rem operations to fast bit logic

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Seems like a good issue for Binaryen's optimizer as well.

**Comment by MaxGraey** [comment]
Yep, I thought about it as well

**Comment by MaxGraey** [comment]
And what you think if replace this:
```ts
    store<u32>(dest     , load<u32>(src     ));
    store<u32>(dest +  4, load<u32>(src +  4));
    store<u32>(dest +  8, load<u32>(src +  8));
    store<u32>(dest + 12, load<u32>(src + 12));
    src += 16; dest += 16; n -= 16;
    src += 16; dest += 16; n -= 16;
```

to:

```ts
    store<u64>(dest     , load<u64>(src     ));
    store<u64>(dest +  8, load<u64>(src +  8));
    src += 16; dest += 16; n -= 16;
    src += 16; dest += 16; n -= 16;
```

for aligned memory copy?

**Comment by dcodeIO** [comment]
Depends whether `dest` **and** `src` are guaranteed to be aligned to 8 bytes at this point.

**Comment by dcodeIO** [comment]
Seems not, as it starts with `if (dest % 4 == 0)`

**Comment by MaxGraey** [comment]
You are right. But for classes and arrays we can expecting 8 byte alignment when mem layout will be finish of course, right? So It's exactly for that case (dest % 8)

**Comment by dcodeIO** [comment]
Well, imagine an Uint8Array. The class would be aligned to 4 bytes because it starts with an i32 length. Its data, which is a separate block, would be aligned to 4 bytes just because that's the minimum alignment (otherwise it'd be 1).

Don't worry too much about these. The `copy_memory` and `move_memory` stuff will be replaced by [bulk memory operations](https://github.com/WebAssembly/bulk-memory-operations) anyway, once these have landed.

**Comment by MaxGraey** [comment]
Ok, I got it

**Comment by dcodeIO** [comment]
These changes are looking good to me. Please include yourself in the [NOTICE file](https://github.com/AssemblyScript/assemblyscript/blob/master/NOTICE#L7) before I merge :)

**Comment by MaxGraey** [comment]
Done!

**Comment by dcodeIO** [comment]
Thanks :)

**Pull request merged**
