### PR TITLE
Emit warning on generic function/class export

### LINKED ISSUE #570: Explicitly restrict exporting generic functions for entry file
main.ts:
```ts
export function foo<T>(a: T): T {
  return a;
}
```
Currently generate wasm module without `foo` function.
Expected: should be compiler error about exporting generic functions/classes are not allowing.

### PR DESCRIPTION
**Pull request by 9oelM**
Without knowledge that exporting a generic function/class is not possible (yes.. I was dumb..), I wasted my time figuring things out on my own. 

When I googled and finally found #570, I wanted to improve this.

- [x] Emit warning on generic function/class export
- [x] Add tests accordingly
- [x] Adjust `runTest` function to consume `stdout`

Would resolve #570

### CODE REVIEW

**Comment by 9oelM** [comment]
Actually, I'm not still sure if we should emit an error or a warning.

**Comment by dcodeIO** [comment]
The way this currently works is that if one does

```ts
export class Foo<T> {
  bar(a: T): T {
    return a;
  }
}
```

while it cannot be automatically compiled due to missing context, if there is

```ts
var foo = new Foo<i32>();
foo.bar(1);
```

somewhere in the code one will still get a `Foo<i32>#bar` export. As such, exporting generics is limited to what's actually reachable from other code and thus present in the binary.

**Comment by MaxGraey** [comment]
@9oelM Yes, I guess warning will be more prefer

**Comment by 9oelM** [comment]
@dcodeIO
I'm sorry, but I haven't fully understood what you said. Could you elaborate a bit more so that I could fix the PR?

**Comment by dcodeIO** [comment]
What I'm trying to get at is that exporting a generic function or class does actually work iff there is a concrete usage of the function or class within the module. Only if there is no concrete usage, there won't be a respective export. Still uncertain how to handle this properly, but perhaps we should attempt to detect generic exports that don't have any concrete usage and only then emit a warning?

**Comment by 9oelM** [comment]
@dcodeIO I get what you mean now. For now, I think it would be a good idea to just emit a warning if there is no concrete usage inside the module itself.

**Comment by dcodeIO** [comment]
One strategy to implement this could be to compile the module normally, inspecting module-level exports right before finishing compilation, emitting the warning if the respective `FunctionPrototype` or `ClassPrototype` has no compiled `.instances`. Somewhat similar to what `Compiler#ensureModuleExports` does, but as a kind of check.

**Comment by 9oelM** [comment]
@dcodeIO Will try that.

**Pull request closed without merging**
