### PR TITLE
Added some quotes from Google I/O 2019 to the README

### PR DESCRIPTION
**Pull request by torch2424**
As discussed in the slack at some point :smile: 

Also, just FYI this happened as well: https://www.programmableweb.com/news/google-recommends-assemblyscript-web-assembly-programming/2019/05/08 :+1:

### CODE REVIEW

**Comment by dcodeIO** [comment]
Thanks, that's a good one :) Feels a bit convoluted to me overall, maybe due to comma count or because the first sentence partly repeats. Any idea?

**Comment by torch2424** [comment]
@dcodeIO Yeah I kinda agree, was thinking that when I submitted, but was like ehhh, it may be fine. But let's change it 😄 

How about we remove: "You [web developers] don't have to learn a new language to learn WebAssembly, which I think, is kind of amazing. [...]"

Giving us:

> You are now able to write WebAssembly, without learning a new language, and harness all these benefits WebAssembly might offer you, I think that is kind of powerful. [...] It [AssemblyScript] is absolutely usable, and very enjoyable! - Surma, [WebAssembly for Web Developers (Google I/O ’19)](https://youtu.be/njt-Qzw0mVY) (May 8th, 2019)

I think the most important piece here is the "usablilty" part. 😄 That way, hopefully, it will no longer appear as a "fun introduction / open source / prototype" language. And I mean that in a good way if that makes sense haha! 👍

**Comment by dcodeIO** [comment]
Yeah, that's perfect :)

**Comment by torch2424** [comment]
@dcodeIO Made the requested changes! :smile:

**Comment by dcodeIO** [comment]
Thanks! :)

**Pull request merged**
