### PR TITLE
Improve build speed

### PR DESCRIPTION
**Pull request by MaxGraey**
Improve build speed using more faster fork of ```ts-loader```'s checker.

On my machine
**Build time before** ~9.6s
**Build time after** ~6.7s

### CODE REVIEW

**Comment by dcodeIO** [comment]
Hmm, I actually like the simplicity of the current setup. It's not meant to be fast but as an "as standard as possible" check that, if anyone would use the TS sources, it just works. Distributed packages would ultimately run the precompiled dist files, of course.

**Comment by MaxGraey** [comment]
It add just [one module](https://github.com/Realytics/fork-ts-checker-webpack-plugin) which move checker in a separate process and this speedup build in some cases significantly. Also I add buildin webpack plugins OccurrenceOrderPlugin, AggressiveMergingPlugin and ModuleConcatenationPlugin which improve bundle size and build time as well. That's all.

**Comment by dcodeIO** [comment]
I am only concerned about the forking checker because it changes the usual TS build process that others might use. I'd favor a vanilla, but of course properly configured if you have improvements, ts-loader instead.

**Comment by MaxGraey** [comment]
ts-loader leave as is. Additional module just move checker pass to another process for parallel and added some features like tslint (actually disable now) and controls about additional output info. So that is not ```ts-loader``` but just hint for it.

**Comment by dcodeIO** [comment]
To recap: I didn't find any significant speed advantages of `OccurrenceOrderPlugin`, `AggressiveMergingPlugin`, and `ModuleConcatenationPlugin` when testing these locally with the code base. Maybe I missed something about these? So most of the speedup seems to come from the forking checker, which I'd like to avoid because it might not always be up to date with latest TypeScript, but I didn't check their exact implementation. In general, I don't see much of a need to improve build speed over guaranteed correctness, but if you have a specific use case why this should be faster, please let me know.

**Comment by MaxGraey** [comment]
The benefits are not so significant, but it can become important when the codebase grows larger. So close this for now

**Pull request closed without merging**
