### PR TITLE
Optimize expandType for JS target

### PR DESCRIPTION
**Pull request by MaxGraey**
- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by dcodeIO** [comment]
With this becoming more common, wdyt of moving these optimizations into a helper? Perhaps something like

```ts
export function i32_load(ptr: usize): i32 {
  return ASC_TARGET
    ? binaryen.__i32_load(ptr)
    : binaryen.HEAP32[ptr >> 2];
}
```

and always use this one instead?

**Comment by MaxGraey** [comment]
I'm not sure. It may have some overhead on JS side

**Comment by dcodeIO** [comment]
Yeah, depends on how well the JIT handles it. Seems rather trivial, though, perhaps it does?

**Comment by MaxGraey** [comment]
Merging. We could return to this later

**Pull request merged**
