### PR TITLE
Use Binaryen's directed inlining

### PR DESCRIPTION
**Pull request by dcodeIO**
This replaces our custom inlining with what's proposed in [this Binaryen PR](https://github.com/WebAssembly/binaryen/pull/1898). Uses a custom Binaryen build for that purpose currently and probably needs some additional work, but pinning it here already so we can have a look how that'd turn out.

### CODE REVIEW

**Comment by MaxGraey** [comment]
@dcodeIO 
https://github.com/AssemblyScript/assemblyscript/blob/directed-inlining/src/resolver.ts#L814

**Comment by MaxGraey** [comment]
Also need fix warnings like `WARNING AS206: Compiling constant with non-constant initializer as mutable.`

**Comment by MaxGraey** [comment]
binaryen has method which could check cost for function and also side effect checker. So what if just check if it return `true` compiler evaluate expression and try get constant?

**Comment by dcodeIO** [comment]
Yeah, precompute would essentially have to evaluate function bodies for this. Not just constant returns, though, but also calls to other functions that might again be inlined etc. (probably everything)

**Comment by MaxGraey** [comment]
Hmm. It seems make sense save some own inline stuff specially for class const fields

**Comment by dcodeIO** [comment]
Plus, seems the build breaks because of webpack running out of memory (or something, again). I didn't see that coming.

**Comment by MaxGraey** [comment]
Try update webpack to latest. It may be this already fixed bug: https://github.com/webpack/webpack/pull/8639

**Comment by MaxGraey** [comment]
It seems same issue:
https://github.com/webpack/webpack/issues/6389

**Comment by MaxGraey** [comment]
Need to try `node --max_old_space_size=4096 ./node_modules/webpack/ ...`

**Comment by dcodeIO** [comment]
Closing in favor of https://github.com/AssemblyScript/assemblyscript/pull/463

**Pull request closed without merging**
