### PR TITLE
fix #2730 compound assignment with post increment in lhs miscompiles

### LINKED ISSUE #2730: Compound assignment with post increment in lhs miscompiles
### Bug description

Compound assignment where the left hand side is an array with a post increment index generates incorrect code.

```ts
let a = new Uint32Array(1);
let v = 0;
a[v++] |= 1234;
```
actually is generating something like
```ts
let a = new Uint32Array(1);
let v = 0;
let v$0 = v;
v += 1;
a[v$0] = a[v] | 1234;
```

### Steps to reproduce

[Editor](https://www.assemblyscript.org/editor#IyFvcHRpbWl6ZT1zaXplJnJ1bnRpbWU9aW5jcmVtZW50YWwmbm9Bc3NlcnQmZGVidWcKZGVjbGFyZSBmdW5jdGlvbiBsb2coeDogdTMyKTogdm9pZApsZXQgYSA9IG5ldyBVaW50MzJBcnJheSgxKTsKbGV0IHYgPSAwOwphW3YrK10gfD0gMTIzNDsKbG9nKGFbMF0pOwojIWh0bWwKPHNjcmlwdCB0eXBlPSJtb2R1bGUiPgpjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKY29uc3QgZXhwb3J0cyA9IGF3YWl0IGluc3RhbnRpYXRlKGF3YWl0IGNvbXBpbGUoKSwgewogIG1vZHVsZTogewogICAgbG9nKGMpIHsKICAgICAgY29uc29sZS5sb2coYyk7CiAgICB9LAogIH0sCn0pCjwvc2NyaXB0Pg==)

Should print `1234`, instead crashes

### AssemblyScript version

0.27.7

### PR DESCRIPTION
**Pull request by Changqing-JING**
fix #2730

### CODE REVIEW

**Comment by CountBleck** [comment]
what the heck

That looks bigger than it's supposed to be.

**Comment by MaxGraey** [comment]
Also, it looks like produces a lot of unnecessary extra locals which do only `local.set $x` / `local.get $x` sequentially and nothing more

**Comment by Changqing-JING** [comment]
@CountBleck @MaxGraey 
Thank you for review. I also agree that this fix is not very beautiful. But unfortunately, after aligned with @HerrCai0907, we think there is no way better than this, except we make big refactor on current code. 

This bug can be easily fixed as supposed because current compile flow emit instruction as pesudo code
```
setter(this, indexStatement, getter(indexStatement));
```
The problem here is, assemblyscript + binary organize statements as tree and compiles from top to down. When compile the setter function, the `getter(indexStatement) ` is just a statement. The compiler can't easily know there is a common indexStatement which need to be compiled in advanced.

To fix this bug, we need
```
index = indexStatement;
tmp = getter(index)
setter(this, index, tmp);
```
To achieve this, we need to hack a bit into the compiled `getter(indexStatement)`. Otherwise, in assemblyscript's top down compile flow, it's difficult to let indexStatement be compiled in advanced. 

This also explained by additional temps are created. But this shall not be a big problem because binary optimization pass can remove them.

**Comment by HerrCai0907** [comment]
I think it is a more generic issue for compound assignment  instead of only for `IndexSignature`

This code will call getA() twice.
```ts
class A {
  a: i32 = 0;
}

function getA(): A {
  trace("get A");
  return new A();
}

export function _start(): void {
  getA().a |= 10;
}
```

**Comment by CountBleck** [comment]
Unless someone else finds a cleaner alternative to whatever this mess[^1] is, this is something I'll definitely have to look into myself, once I have the time.

[^1]: Attaching a cache to an AST node is straight up weird, and the way it's used seems like a hack around expressions being compiled twice. Another hack is the patching of previously generated Binaryen IR so that it uses a local. `CompiledExpression` in general seems like something that should/could be removed (it's not used in any other part of AS, nor can it be effectively used in transforms AFAIK).

**Comment by Changqing-JING** [comment]
Heacking the previsouly generated IR problem is solved, which makes the commit clearer. But this still can't solve the `getA().a |= 10;` problem. So I didn't update this to PR. I will also think about a better solution.
https://github.com/Changqing-JING/assemblyscript/commit/a3cb730ccdb8a2787025c7f78a4878ca58834859

**Pull request closed without merging**
