### PR TITLE
Rename Uint64Array to BigInt64Array. Add BigInt stub for portable

### PR DESCRIPTION
**Pull request by MaxGraey**
BigInt now landed in V8 6.6 and 6.7 (without extra flag). So I propose adopt some long integers stuffs for this feature.

Proposal spec detail: https://github.com/tc39/proposal-bigint

### CODE REVIEW

**Comment by dcodeIO** [comment]
Isn't there a bit more to this, like the `n` postfix and support for `BigInt` in general? I had the impression that we'd ultimately need to have both, while Uint64Array takes native i64s and BigInt64Array takes whatever we decide to implement for BigInts as a compatibility fallback (i.e. because a value can't be both an i64 and a BigInt at the same time).

**Comment by MaxGraey** [comment]
May be good idea to create some custom plugin for Typescript and during AST walking just add `n` suffix for i64/u64 literals?

**Comment by dcodeIO** [comment]
There might be ways to support compilation to TypeScript by converting i64s that way when always wrapping such values with `.asUintN`, but as bigints might be larger than 64-bits, I don't see a proper way to make them interoperable when compiling to WebAssembly. Hence my impression that we'd ultimately have both variants.

**Comment by dcodeIO** [comment]
Yeah, WASM<->JS interop totally makes sense with them.

**Comment by dcodeIO** [comment]
Closing in favor of https://github.com/AssemblyScript/assemblyscript/issues/117 :)

**Pull request closed without merging**
