### PR TITLE
Add Properties To Memory for Each View

### PR DESCRIPTION
**Pull request by willemneal**
Add `U8, I8, ...` properties to memory that wrap the internal buffer with the corresponding view.

### CODE REVIEW

**Comment by MaxGraey** [comment]
Hmm, interesting. But I worry about performance. Could you make some perf measurements for `before` and `after` this changes? And also how this affect to size especially for minified loader

**Comment by willemneal** [comment]
Is there a benchmark that I could use?  Or do you just want a simple one.  I mostly changed all the internal views, e.g. `new Uint32Array(memory.buffer)` to use the property, which small function call, which I'm sure will be optimized by the runtime.  So I for now is it okay to just run the tests w/ and w/o?

I'm also unsure what you mean for minified loader?  I didn't know that it was.  Non-minified it added 800 bytes.  But this functionality was previously available and users will probably be fine with the size.

**Comment by MaxGraey** [comment]
I checked size.
Before: `The minified output (6432 bytes, saved 56.91%)`
After: `The minified output (6751 bytes, saved 57.14%)`

I used this tool: https://skalman.github.io/UglifyJS-online

So this changes add extra 319 bytes and probably could slowdown code (while jit not warmsed up)

**Comment by dcodeIO** [comment]
One of the learnings in https://github.com/AssemblyScript/assemblyscript/pull/810 was that wrapping a buffer in `new TypedArray` seems to have no particular performance implications in modern VMs as one might expect by using `new` (like an allocation happening or similar), and as such is preferable over providing convenient views while also eliminating the need to check for growing memory. So one important question is whether returning a `new TypedArray` has other performance implications? And ofc if the convenience introduced outweighs the code size increase in typical cases.

**Comment by willemneal** [comment]
Here's an interesting test I made comparing `new TypedArray` vs `TypedArray.from`.  I'll try adding a caching test next

**Comment by MaxGraey** [comment]
@willemneal thanks for sharing!

Chrome:
```
new Uint8Array(buffer):  36,229,083 ops/sec
Cache Test p = 0:  37,854,347 ops/sec
```
Which pretty expected that's why we decide remove `memcheck` helper

**Comment by willemneal** [comment]
Firefox 68:

Test | Ops/sec
-- | --
x = new Uint8Array(buffer); | **2,341,094 ±4.14%** 81% slower
x = Uint8Array.from(buffer); | **1,458,705 ±5.03%** 88% slower
getArray(0) | **12,451,138 ±4.61%** fastest
getArray(0.25) | **11,004,172 ±5.79%** 13% slower
getArray(0.5) | **9,533,480 ±5.57%** 24% slower
getArray(0.75) | **9,510,627 ±6.15%** 25% slower
getArray(1) | **9,366,052 ±4.75%** 25% slower

So weird!

**Comment by MaxGraey** [comment]
Due to some bad [results in FF](https://github.com/AssemblyScript/assemblyscript/pull/815#issuecomment-528561200) I will close this

**Pull request closed without merging**
