### PR TITLE
fix: ignore this

### PR DESCRIPTION
**Pull request by CountBleck**
This is a dummy commit to create a new release.

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by HerrCai0907** [comment]
Do you know why our release pipeline does not work?

**Comment by HerrCai0907** [comment]
I found the reason, [aspublish](https://github.com/AssemblyScript/aspublish?tab=readme-ov-file#commit-format) requires `breaking / feat / fix` prefix to identifier the version upgrade. Maybe we need to create an action and check the PR title to avoid this weird empty PR. WDYT?

**Comment by CountBleck** [comment]
@HerrCai0907 That would be nice, but if a PR only has one commit, the default commit title in the merge commit is based off of that commit's title, not the PR title (see #2826).

**Comment by HerrCai0907** [comment]
> @HerrCai0907 That would be nice, but if a PR only has one commit, the default commit title in the merge commit is based off of that commit's title, not the PR title (see #2826).

Yes. But we can switch the merge strategy in configuration page. I am not sure who has the access to setup it. Maybe it needs @dcodeIO or @MaxGraey

**Comment by CountBleck** [comment]
@HerrCai0907 that doesn't sound ideal...

**Comment by HerrCai0907** [comment]
Configuration like this:
image

Why is it not ideal?

**Comment by dcodeIO** [comment]
Changed the setting to "Pull request title" as suggested

**Comment by CountBleck** [comment]
> Why is it not ideal?
> 

@HerrCai0907 Oh I misunderstood. That's perfect!

**Pull request merged**
