### PR TITLE
Remove call_indirect & call_direct from definitions

### PR DESCRIPTION
**Pull request by MaxGraey**
Relate to #1016

### CODE REVIEW

**Comment by dcodeIO** [comment]
Thanks!

**Comment by jtenner** [comment]
Question. How can we do dynamic dispatch in the `AssemblyScript/node` library without access to `call_indirect`?

**Comment by jtenner** [comment]
https://github.com/AssemblyScript/node/pull/18/files#diff-886f5b42d066f7f1c5dbea39704253c1R43

**Comment by MaxGraey** [comment]
@jtenner https://github.com/AssemblyScript/assemblyscript/issues/1016#issuecomment-567680924

**Comment by jtenner** [comment]
Thanks for this info!

**Pull request merged**
