### PR TITLE
Support non-null assertion expression `x!`

### PR DESCRIPTION
**Pull request by andy-hanson**
Adds support for TypeScript's `x!` non-null assertion expression. If `x` is of type `T | null`, this is equivalent to `<T> x`.
(Documentation: See "Type guards and type assertions" at in the TypeScript [handbook](https://www.typescriptlang.org/docs/handbook/advanced-types.html))

This does not come with a runtime check for consistency with type assertions. See #234.

### CODE REVIEW

**Comment by dcodeIO** [comment]
cc @MaxGraey

**Comment by MaxGraey** [comment]
Great! We also discussed with @dcodeIO about new semantic meaning exclamation operator for unchecked index accessors for array like write `var item = arr![5]` instead `var item = unchecked(arr[5])`.

**Comment by dcodeIO** [comment]
Remains the question what we'll do with unchecked accesses then (what `unchecked(...)` currently does). Not sure that this can be combined in a good way, but this issue also makes clear that we should probably not use `x!` for that purpose anyway. @MaxGraey ?

**Comment by MaxGraey** [comment]
It is necessary to formalize how semantically an "unchecked case" will be handled in combination with non-null assertion. If you consider each case for array access, then you can get:

1). Array is non-nullable `var arr: Array`:
  - checked access as usual: `arr[index]`;
  - unchecked access: `arr![index]`;

2). Array is nullable `var arr: Array | null`:
  - checked access: `arr![index]`;
  - unchecked access: `arr!![index]` (double exclamation);
  - should throw compilation error: `arr[index]`;

What do you think?

**Comment by MaxGraey** [comment]
Another variant for "unchecked" index access of array is `arr[index!]`.

**Comment by dcodeIO** [comment]
Not a bad idea. That could work, on the index, as it should never be nullable anyway due to being an i32.

**Comment by andy-hanson** [comment]
>

See #233 -- IMO `i32 | null` should be a valid type and could be implemented by passing an `i32` and `boolean` together. Otherwise how do you implement `Map<T, i32>.get`, or any other generic function returning `T | null`?

**Comment by dcodeIO** [comment]
There are some occasions in the sources where a `.has` is performed before a `.get` because of this (with `.get` resulting in `unreachable` if the value wouldn't exist). I haven't yet updated a lot of them. That's of course inefficient, because it involves two hash lookups on a match, but since there's no `undefined` we could use, I didn't see a good alternative. Maybe something like `i32 | null` could be modeled once the multi value spec lands (as an i32 and bool as you suggest).

**Comment by dcodeIO** [comment]
Sorry for not following up here. Wasn't quite comfortable with the implementation but couldn't tell why. Now implemented in https://github.com/AssemblyScript/assemblyscript/pull/443 as another kind of assertion. Thank you anyway!

**Pull request closed without merging**
