### PR TITLE
Add precompute for static array's element if necessary

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by MaxGraey** [comment]
@dcode Is it right approach?

**Comment by dcode** [comment]
I think you meant to tag @dcodeio. I'm happy to weigh in,  if you really want my opinion, however.  I have no shortage of opinions ;-)

**Comment by MaxGraey** [comment]
Ahaha, you are right=) My bad! Sorry I bothered you.

**Comment by dcodeIO** [comment]
I have a couple of changes locally that include a fix. There's quite some stuff wrong with GC there ^^

**Comment by MaxGraey** [comment]
Great! Good to know. I really need this fix =)

**Comment by dcodeIO** [comment]
Should be fixed in https://github.com/AssemblyScript/assemblyscript/commit/631478c7c919123a4be8fcb66bfd7ece7f49bb2c

**Pull request closed without merging**
