### PR TITLE
Add 'Loader' example

### PR DESCRIPTION
**Pull request by dcodeIO**
As promised on the Discord, I've made an example covering the very basics of utilizing the loader.

* Example 1: Passing a string from WebAssembly to JavaScript.
* Example 2: Passing a string from JavaScript to WebAssembly.
* Example 3: Calling JavaScript imports with WebAssembly strings.
* Example 4: Passing an array from WebAssembly to JavaScript.
* Example 5: Passing an array from JavaScript to WebAssembly.
* Example 6: WebAssembly arrays of WebAssembly strings.
* Example 7: Using custom classes.

This should give everyone interested a quick start with recipes to perform the most common tasks. As usual, my perspective might be a little trees in the woods here, so let me know where I am assuming something that isn't trivial :)

### CODE REVIEW

**Comment by MaxGraey** [comment]
I guess will be great also add 7th example which demonstrate how do something like this:
```ts
class Complex {
   re: f64
   im: f64
};

export function getComplexMatrix(): Complex[][] {
  ...
}
```

**Comment by dcodeIO** [comment]
Initially considered making another example like "Loader Advanced", but I think you are right and I should just add it here, as there aren't a lot of advanced custom classes scenarios anyway.

**Comment by MaxGraey** [comment]
Do you think move it to `AssemblyScript/examples` repo?

**Comment by dcodeIO** [comment]
Yeah, figured that a separate repo makes sense with increasing example count. Loader example is here: https://github.com/AssemblyScript/examples/tree/master/loader

**Pull request closed without merging**
