### PR TITLE
More StringRef operation stubs

### PR DESCRIPTION
**Pull request by MaxGraey**
- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by dcodeIO** [comment]
Not seeing these in wasm.h on the Binaryen end, hence not sure what we'd use them for?

**Comment by MaxGraey** [comment]
It just not implemented yet. But should according to spec: https://github.com/WebAssembly/stringref/blob/main/proposals/stringref/Overview.md#binary-encoding

**Comment by MaxGraey** [comment]
Also check a parser: https://github.com/WebAssembly/binaryen/blob/main/scripts/gen-s-parser.py#L607

**Comment by MaxGraey** [comment]
Hmm. But About `StringConcat`, `stringview_wtf8.advance` and `stringview_wtf16.get_codeunit`?

**Comment by dcodeIO** [comment]
A concrete example of how this is typically structured, using `StringAs` which has one `ExpressionId` with multiple ops

```
ExpressionId.StringAs // StringAs wrapper
 * StringAsOp.WTF8    // StringAs wrapper with op=WTF8
 * StringAsOp.WTF16   // ...
 * StringAsOp.Iter
```

and `StingConst`, which only has an `ExpressionId`:

```
ExpressionId.StringConst // StringConst wrapper
```

**Comment by MaxGraey** [comment]
Ok,I will close this

**Comment by dcodeIO** [comment]
To answer your question:

* `string.concat` is represented by a `StringConcat` wrapper class with (so far missing) `ExpressionId.StringConcat`. No ops.
* `stringview_wtf8.advance` is represented by a `StringWTF8Advance` wrapper class with (so far missing) `ExpressionId.StringWTF8Advance`. No ops.
* `stringview_wtf16.get_codeunit` is represented by a `StringWTF16Get` wrapper class with (so far missing) `ExpressionId.StringWTF16Get`. No ops.

**Pull request closed without merging**
