### PR TITLE
Add erf and erfc for NativeMath

### PR DESCRIPTION
**Pull request by MaxGraey**
Error Function and Complementary Error Function is not including in JavaScript's Math but these special functions very important for statistics and other analysis and simulations due to erf / erfc is gaussian's integral.

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by dcodeIO** [comment]
How important is it to have these functions in stdlib instead of in a package one can install? Like, I see that these may be valuable, but since I so far didn't need them myself, and wouldn't expect them to be in a JS-like stdlib, I'd like to discuss these APIs and their usefulness before committing to them :)

**Comment by MaxGraey** [comment]
`erf`/`erfc` include usually in all standard libraries except Lua, JavaScript and Java.

JavaScript have a lot of libraries for it:
https://www.npmjs.com/search?q=erf
https://mathjs.org/docs/reference/functions/erf.html
https://gist.github.com/kcrt/6210661

`erf` special functions hard to implement properly or efficient so I think it will be really useful have official well tested and optimized function in our standard library. In addition, we already have a small set only specific to AssemblyScript Math functions. For example, Math.sincos has already been appreciated by many developers, although it is not in the standard JavaScript library. And I don’t think we’ll lose anything if we include these functions in the standard library.

**Comment by dcodeIO** [comment]
Given that other stdlibs have these, I would be OK with adding support here as well. What do you think of bringing this up at a meeting, to be sure? :)

**Comment by MaxGraey** [comment]
> What do you think of bringing this up at a meeting, to be sure? :)

Sure! It makes sense to discuss this with everyone

**Pull request closed without merging**
