### PR TITLE
update ts-node to 8.6.2

### PR DESCRIPTION
**Pull request by MaxGraey**
Due to https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

### CODE REVIEW

**Comment by MaxGraey** [comment]
btw ts-node was included in `devDependencies` and `dependencies`

**Comment by dcodeIO** [comment]
> update ts-node to 8.6.2

Last time i checked upgrading to >6 led to subtle errors as described [here](https://github.com/TypeStrong/ts-node/issues/620). Wondering if that's not an issue anymore?

> btw ts-node was included in devDependencies and dependencies

The duplicates are intentional as an indicator that these are needed on `npm install AssemblyScript/assemblyscript`, but not on `npm install assemblyscript`. Handled by [prepublish](https://github.com/AssemblyScript/assemblyscript/blob/master/scripts/prepublish.js#L27).

**Comment by MaxGraey** [comment]
> Last time i checked upgrading to >6 led to subtle errors as described here.

Not sure, but you could check this. I didn't see any errors

**Comment by dcodeIO** [comment]
Fixed by https://github.com/AssemblyScript/assemblyscript/pull/1170

**Pull request closed without merging**
