### PR TITLE
fix: export default in namespace #2200

### PR DESCRIPTION
**Pull request by technohippy**
⯈fix: #2200 

Now the same error message as TS is used.

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by romdotdog** [comment]
I think changing the message for this error could be beneficial, wdyt? Do you think it's confusing? cc: @dcodeIO

**Comment by dcodeIO** [comment]
I guess the reference to "ECMAScript-style module" can be dropped, as this is all AS supports anyway. Perhaps: "A default export can only be used in a module." Still about the same message, but less over-precise.

Another thought: I wonder that a `NodeKind.EXPORT` even ends up in namespace initialization. Seems brittle. Can this perhaps be checked during parsing already, not appending the export in this place?

**Comment by romdotdog** [comment]
I was thinking something more like `A default export cannot be used in a namespace.` or maybe even better `A default export can only be used in the top level.` unless there is another case where they can be used?

**Comment by technohippy** [comment]
`TS1258: A default export must be at the top level of a file or module declaration.` may be the one we want.

**Comment by technohippy** [comment]
hmm... I choose `A default export can only be used in a module.` for now. Anyone can change this anytime.

**Comment by technohippy** [comment]
@dcodeIO Test / Bootstrap throws a strange error now. `npm run bootstrap` can run on my local env. Do you have any idea?

```
TypeError: WebAssembly.compileStreaming is not a function
    at file:///home/runner/work/assemblyscript/assemblyscript/build/assemblyscript.debug.js:2[23](https://github.com/AssemblyScript/assemblyscript/runs/6088770012?check_suite_focus=true#step:6:23)3:21
    at file:///home/runner/work/assemblyscript/assemblyscript/build/assemblyscript.debug.js:2238:3
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:[24](https://github.com/AssemblyScript/assemblyscript/runs/6088770012?check_suite_focus=true#step:6:24))
    at <anonymous> (/home/runner/work/assemblyscript/assemblyscript/cli/index.js:47:20)
```

**Comment by romdotdog** [comment]
Only one thing on the logs caught my eye: `Node v18.0.0` as opposed to the first run which used `Node v17.9.0`. Needs further testing.

**Comment by dcodeIO** [comment]
Fixed the CI error in #2274. Merging main should resolve the error in this PR as well.

**Comment by dcodeIO** [comment]
Thanks!

**Pull request merged**
