### PR TITLE
chore: Set up semantic release

### PR DESCRIPTION
**Pull request by dcodeIO**
As discussed on Slack and in https://github.com/AssemblyScript/assemblyscript/issues/1331, this PR removes our custom release logic, including publishing nightlies which isn't necessary anymore after the change, and installs [semantic-release](https://github.com/semantic-release/semantic-release) (currently configured to perform dry runs in case something goes wrong).

Commit format would then be:

* `fix: Message` for a patch (wondering what will happen there with version < 1)
* `feat: Message` for a minor
* `BREAKING CHANGE: Message` (or used as a footer) for a major

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by dcodeIO** [comment]
Looking up the `v0` problem revealed that they are apparently not taking semantic releases as serious as their package name suggests :( https://github.com/semantic-release/semantic-release/issues/1507

**Comment by MaxGraey** [comment]
Btw it seems it could be with optional scope like:
`fix(parser): message`
`feat(std): message`
In this case will be great have whole list of conventions

**Comment by dcodeIO** [comment]
Yeah, using a scope seems good. I'm however unwilling to force out a `v1` just because of using this tool, so I'm tending to discard this PR and roll our own.

**Comment by dcodeIO** [comment]
Now uses my fork of `semantic-release` that has a `--prev1` command line option enforcing releases to stay in the `v0.x.x` range. Turned out this can be achieved with just [a few lines of code](https://github.com/dcodeIO/semantic-release/commit/ce466172ae4a35d755514c4be3d242d330c4da72).

**Comment by dcodeIO** [comment]
Merging, but letting it perform dry runs initially so I can check the logs, hence no actual releases just yet. Going to activate once sufficiently confident that it's working :)

**Pull request merged**
