### PR TITLE
BREAKING CHANGE: Remove support for WASI

### PR DESCRIPTION
**Pull request by dcodeIO**
For us, WASI's exclusionary design is a regression and even though we voiced our needs, suggestions and concerns many times over the last years, its subgroup keeps ignoring, attacking and excluding us. Since there is no reasonable path forward anymore and future expectations are solely negative, the reasonable consequence is to stop officially supporting WASI's harmful efforts.

For those who have no other choice than to use such interfaces and related products, we are working on a custom shim that will become available under https://github.com/AssemblyScript/wasi-shim somewhen after 0.21 has been released.

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Review by trusktr — APPROVED** [review]
Anyone who needs WASI support can polyfill web APIs on that side. 👍

**Comment by JairusSW** [comment]
I totally agree. 👍🏼

**Comment by dcodeIO** [comment]
Thanks for the feedback! Still working on the shim, but it's almost ready so it should be released soon™ 🙂

**Comment by JairusSW** [comment]
Awesome! I have been looking forward to seeing these changes appear in AS for quite a while now :)

**Pull request merged**
