### PR TITLE
Implement StaticArray<T> as a way to have static data

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR adds a more efficient variant of arrays, named `StaticArray<T>` to the standard library that, unlike normal arrays, does not have a level of indirection, hence

* Has more efficient indexed operator overloads (half of the memory accesses)
* Yields less noise in text and binaries since one doesn't have to cache `.dataStart`
* Has 32 bytes less overhead due to skipping the Array header incl. its GC header
* Cannot resize automatically, with an interface similar to `ReadonlyArray<T>` in TS
* Yet is AOT incompatible to normal `Array<T>`, `ReadonlyArray<T>` or `ConcatArray<T>` in TS due to a different layout in memory, hence uses a new name

From a technical point of view, one can think of it as a raw `ArrayBuffer` with an attached element type. It's especially useful in low-level code like our standard math library where it eliminates most of the overhead introduced by having no other option than using `Array<T>` for precomputed lookup tables. There are some other use cases benefiting from it, like the n-body example where getting rid of the level of indirection yields overall better performance, that otherwise can only be achieved by resorting to low-level loads and stores and caching `.dataStart`.

Also somewhat related to https://github.com/AssemblyScript/assemblyscript/pull/1121 in that we have more options now how to go forward with `.dataStart`, potentially replacing it with `.buffer + .byteOffset` to match the spec more closely.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Instead of `FixedArray<T>` this now implements `ReadonlyArray<T>`, which is similar but immutable, and binds it to const assertions of the form `[1, 2, 3] as const`. Of course this has its implications, like we don't yet support anything else than const array literals and we lose the mutability feature of the initially proposed `fixed<T>` builtin, but it still seems good enough to solve the underlying requirement of being able to add truly static data segments where we need them.

In the standard library, we typically use these together with manual unsafe `load/store` so the immutability part isn't relevant there anyway, and since `ReadonlyArray<T>` and `FixedArray<T>` are layout-compatible, a user can decide to `changetype<FixedArray<i32>>(someReadonlyArrayI32)`. There has also been the suggestion to make `FixedArray<T> extends ReadonlyArray<T>`, but this is unsafe in that something that is intended to be readonly can be mate mutable in safe syntax like `someReadonlyArrayI32 as FixedArray<i32>`, so I left that out. The other way around might be possible, though, by throwing in everything that would mutate.

**Comment by dcodeIO** [comment]
From looking at the code, while `as const` is fine to have, I'd favor a more concise variant like

```ts
const readonlyArray = [1,2,3] as ReadonlyArray<T>;
const fixedArray = [1,2,3] as FixedArray<T>;
```

respectively

```ts
const readonlyArray: ReadonlyArray<T> = [1,2,3];
const fixedArray: FixedArray<T> = [1,2,3];
```

which, to my surprise, seems to type-check just fine since these classes are structure compatible to `Array<T>`. And it appears that `[1,2,3] as readonly` is also a thing in TS.

**Comment by MaxGraey** [comment]
Yeah, `as const T[]` / `as const` is just more general alternative of `as ReadonlyArray<T>`. But `as const` could also apply to records (inline objects)

**Comment by MaxGraey** [comment]
btw `readonly T[]` and `ReadonlyArray<T>` should be synonyms same as `T[]` and `Array<T>`

**Comment by dcodeIO** [comment]
For some reason `as const i32[]` doesn't type-check for me. Is that expected?

**Comment by MaxGraey** [comment]
You're right it should be `as readonly i32[]` in TS. And `as const` works only with inferred arrays

**Comment by dcodeIO** [comment]
So it seems that

* `readonly` is a type modifier only valid for arrays and tuples (nothing to do with assertion expressions specifically)
* `as const` is a special case of an assertion expression, deriving an exact immutable type

From a purist perspective, both of these do not map well to AssemblyScript, which makes me even more favor something explicit like `as ReadonlyArray<i32>` or `as FixedArray<i32>` over them.

**Comment by MaxGraey** [comment]
Yes, "readonly" and `Readonly<T>` is just modifiers and simple compile time artefact same as `public`, `protected` and etc, but `ReadonlyArray<T>` is different interface / class.

**Comment by MaxGraey** [comment]
In TS:
```ts
const arr1 = [1, 2, 3] as ReadonlyArray<number>; // infers as "readonly number[]"
const arr2 = [1, 2, 3] as const; // infers as "readonly [1, 2, 3]" tuple
```

**Comment by dcodeIO** [comment]
Yeah, that `readonly i32[]` -> `ReadonlyArray<i32>` equality worries me the most, since a `ReadonlyArray<i32>` has a completely different layout than `i32[]`, and TypeScript might expect these to be somewhat compatible due to structural compatibility. Again, a distinct `FixedArray` would be more correct there, with `ReadonlyArray<i32>` using actual `Array<T>` layout.

**Comment by dcodeIO** [comment]
Alright, most likely unpopular conclusion: I have a feeling that if we force `ReadonlyArray<T>` to a different layout than `Array<T>` now we might eventually wake up to a situation similar in nature to the `===` inconsistency, for instance because arrays can't be assigned back and forth or are not as interoperable as one would expect in TS once we have a `readonly` type modifier for example.

Hence I removed `ReadonlyArray<T>` again, made `as const` a `Not implemented` stub (at least we can parse it now) and settled for `FixedArray<T>` with an `as fixed<T>` shorthand for convenience. This gives us the functionality we need without taking any risks.

**Comment by jtenner** [comment]
So the final decision is with `FixedArray<T>`? Count me excited!

**Comment by dcodeIO** [comment]
We can use `as fixed`, but at this point the corresponding TS type (for compat) would have to be `type fixed = any[]` or something, losing type information. With our own language server, probably, at the expense of being incompatible with TS semantics.

**Comment by MaxGraey** [comment]
The more I look at `FixedArray`, the more I'm afraid it's lead to unnecessary complexity. I think most users will not use it due to restrictions or just ignorance of its existence because it non-standard type. Saving 16 bytes doesn't seem like such a big deal to me either compare to complexity. The only place it can be useful is for our internal static lookup tables. But in this case just declare `raw memory segment` without any extra types and interfaces will be enough.

**Comment by dcodeIO** [comment]
There is more than just size this tries to solve. To me it's even more important that it gets rid of the additional layer of indirection that comes from normal arrays being resizable, and by doing so also gets rid of unnecessary globals and locals dealing with `.dataStart`, reducing quite a bit of noise in generated text and binaries. Also, size saving is more along the lines of 32 bytes (Array<T> GC header + Array<T> data, as 16 bytes is TLSFs granularity). Ofc we can technically save another 16 bytes by making it unmanaged and static only, but by giving it a GC header we gain the ability to use it in safe code, pass it around, and construct it at runtime from non-static data like objects, like for example in n-body where it gets AS perf on par with Rust.

**Comment by MaxGraey** [comment]
Yeah, FixedArray is similar to "slice" type in other languages (including Rust) and it totally makes sense but not sure as explicit data type but rather, as an implicit internally optimizing view for ordinal arrays, hmm... But this require sophisticated optimizations and decisions which that we do not yet have. So maybe we can stop at FixedArray as a compromise solution.

**Comment by jtenner** [comment]
My vote is in for `FastArray<T>` because it looks like it's possible to put managed references in it. I really like that the data type is managed, too.

Is it possible to make a class both Unmanaged and managed at the same time? Compile the static data with @unmanaged and the managed version with another Type?

`StaticArray<T>` and `FastArray<T>` both together solve slightly different problems.

**Comment by jtenner** [comment]
And... Maybe forgive me for suggesting crazy, but now that we have package management, maybe someone could just implement FastArray in their own package? 😊

**Comment by MaxGraey** [comment]
Also possible names:
`ArrayView<T>`
`SlicedArray<T>`
`Slice<T>`
`Arr<T>`

**Comment by dcodeIO** [comment]
`StaticArray<T>` would be fine for me as well, just sad that we can't have `as static<T>` due to `static` being a reserved keyword in strict mode. We can still name it `StaticArray` and remove the convenience helper.

**Comment by MaxGraey** [comment]
`StaticArray<T>` perhaps the best due to it contain Array and consistent with TypedArray. But it petty long. Wdyt about `Seq<T>` (like just raw sequence elements in memory)? Btw this also abstract [data type in Haskell](https://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Sequence.html#t:Seq)

**Comment by dcodeIO** [comment]
Would prefer `Sequence<T>` over `Seq<T>` if we decide for that. The latter looks too abbreviated to me, compared to the names of other standard library elements. Currently leaning into the direction of `StaticArray<T>` without a convenience helper, though.

**Comment by MaxGraey** [comment]
Okay, so let's call it StaticArray =)

**Comment by MaxGraey** [comment]
Btw Typescript has `ConcatArray<T>` which looks like exactly what we need!

**Comment by MaxGraey** [comment]
interface for [ConcatArray](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L1204)

**Comment by dcodeIO** [comment]
Has similar problems like `ReadonlyArray`, though, in that some `Array` methods in TS are typed to receive a `ConcatArray`, as a form of describing a minimal interface that works with a particular array method. But our `FixedArray` isn't compatible with `Array`, so reusing something that is meant to be compatible can and probably will backfire, like `===`.

**Comment by MaxGraey** [comment]
On TS `ConcatArray` is really special array which used only for spread types like:
```ts
function foo(...args: ConcatArray<i32>) {
}
```
So it basically `arguments` in ES5 which also pretty limit type and require `.slice(0)` to convert to normal Array so it could works

**Comment by dcodeIO** [comment]
It's for example used by TS to describe the argument to `Array#concat` and `ReadonlyArray#concat`, both of which would not be able to deal with both `Array` and `FixedArray` (or our version of `ConcatArray` for that matter) alike. What I'm trying to get at is that these interfaces are designed to be somewhat compatible to `Array`, in the sense of a subset, which isn't the case in AS. In AS, these may have the same methods, but a different layout.

**Comment by MaxGraey** [comment]
`ConcatArray` iuses as Variadic type for `concat`: 
`concat(...items: ConcatArray<T>[]): T[]`

TS don't mix Array & ConcatArray. `ConcatArray` has really special meaning

**Comment by dcodeIO** [comment]
But TS would be fine with a user providing our variant of `ConcatArray` to `Array#concat`, yet that would be a compile error in AS because `#concat` needs something with actual `Array` layout. It's just not safe to hijack these. If we implement `ConcatArray` or `ReadonlyArray`, these should be layout-compatible to `Array` to avoid any potential issues.

**Comment by MaxGraey** [comment]
I guess `ConcatArray` is just ArrayLike onbject with [isConcatSpreadable property setted to true](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/isConcatSpreadable) but not real Array and shouldn't be compatible. As well as [`arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) which is also just ArrayLike object

**Comment by dcodeIO** [comment]
I'll go ahead now and rename this abomination of an array to `StaticArray` fwiw. I hope we can agree on this, and I also hope that the technical aspects mentioned here will somehow go away in the future, but unfortunately are a problem as of today. When that happens, I'll be more than happy to revisit this, but at this point I worry more that we'll rather go stale by means of arguing about details too much than getting anything done.

**Comment by MaxGraey** [comment]
sure. It was just suggestions and small brainstorm for alternative point of view

**Comment by dcodeIO** [comment]
Updated the opening post with what I hope is a good summary of the choices made :)

**Pull request merged**
