### PR TITLE
Switch release process to aspublish

### PR DESCRIPTION
**Pull request by dcodeIO**
Retires semantic-release, which unfortunately is [broken](https://github.com/semantic-release/semantic-release/issues/1666) for us currently, and uses [aspublish](https://github.com/AssemblyScript/aspublish).

Aspublish is essentially a minimal replacement for what semantic-release was doing for us, but it only does what typical AS packages need (changelog -> GitHub release -> npm package) in what's essentially a single file with a couple functions, so if there are release issues in the future, we can easily fix these ourselves. Also gets rid of ~5700 lines of package-lock.json and relieves me from maintaining a fork of semantic-release due to my [suggestion](https://github.com/semantic-release/semantic-release/pull/1574) to handle versions less than 1.0.0 without upping to 1.0.0 being rejected.

What we are losing is bot comments on issues and PRs included in a release, which was a nice touch for contributors, but not so much for maintainers due to having to click through all of them in the morning to see if there are any human comments in between. Fine for me as long as we keep posting final human comments :)

Note that this is not a rant about semantic-release, which is a great tool with many configuration options for many more use cases, and if it is working for you it's a solid choice.

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by MaxGraey** [comment]
So huge dependencies cleanup =)

**Comment by dcodeIO** [comment]
😄 https://github.com/npm/cli/issues/1973

**Comment by MaxGraey** [comment]
Is it possible downgrade to `npm 6.x` for publish?

**Comment by dcodeIO** [comment]
Alright, that worked, but looks that doing `npm version` in a sub-package doesn't do anything useful. Will probably have to revive the postversion script.

**Pull request merged**
