### PR TITLE
tests: Add tests for StaticArray

### PR DESCRIPTION
**Pull request by saulecabrera**
Adds the following missing tests for StaticArray:

- constructor
- fromArray
- concat (static)
- slice (static)
- concat (instance)
- includes
- indexOf
- join + toString

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by saulecabrera** [comment]
@dcodeIO @MaxGraey one thing that I noticed while working on this is that we have `isArray` for which the documentation states the following:

> Tests if the specified type or expression can be used as an array. Compiles to a constant.

But `isArray`  returns false with `StaticArray`, which can be used as an array (I know that it technically doesn't extend it) but this seems inconsistent/counterintuitive. Should this be fixed in the docs? 

There's also `isArrayLike`, and in this case, `isArrayLike` returns `true` for a `StaticArray`, but there is no documentation for this one, is there a reason for this? Or should we document it?

**Comment by saulecabrera** [comment]
@dcodeIO 👋 any thoughts on this?

**Comment by dcodeIO** [comment]
It's a bit unfortunate that `StaticArray` is somewhat incompatible with normal `Array`s, even though that's about the point to introduce it. My immediate thought was that we should have named it differently, something without an `Array` in it perhaps, but now we are kinda stuck with it. So, to be honest, I don't know what to do, but documenting the difference certainly makes sense :)

**Comment by saulecabrera** [comment]
> So, to be honest, I don't know what to do, but documenting the difference certainly makes sense :)

That's a valid outcome of this discussion, I think that as long as the differences are pointed out correctly then the name becomes less relevant. That said, I didn't intend to make my comment above a blocker to merge this, it was mostly observation. I'll follow up with a documentation issue/PR.

**Review by MaxGraey — APPROVED** [review]

**Comment by dcodeIO** [comment]
Thanks! :)

**Pull request merged**
