### PR TITLE
Implement non-null assertions

### PR DESCRIPTION
**Pull request by dcodeIO**
Similar to https://github.com/AssemblyScript/assemblyscript/pull/235, but implemented as another kind of assertion.

### CODE REVIEW

**Comment by MaxGraey** [comment]
Is it valid?
`return foo.bar!!;`
`arr!!![0]`

**Comment by MaxGraey** [comment]
How about that?:
```ts
export function testFn3(fn?: (() => Foo | null)): Foo | null {
  return fn!();
}
```

**Comment by dcodeIO** [comment]
That fails to compile because we don't support `fn?:`. The following with an initializer as we require it errors for other reasons, though:

```ts
export function testFn3(fn: (() => Foo | null) | null = null): Foo | null {
  return fn!();
}
```

```
ERROR AS200: Conversion from type 'usize' to '(() => Foo | null) | null' requires an explicit cast.
```

Something off with assigning `null` to a function type as it seems, but probably an issue on its own.

**Comment by MaxGraey** [comment]
Yeah. This relate to how handle of `undefined` type. Because `arg?: Foo` produce `arg: Foo | undefined`. So this make sense for different PR. But first need decide if we need support this semantics and may be force it to `null`? Like `arg?: Foo` same as `arg: Foo | null`

**Comment by dcodeIO** [comment]
Leads us to nullable basic types as well then, like `a?: i32`. Might be too early to decide.

**Comment by MaxGraey** [comment]
Same as `a: i32 | null`. Currently this valid but not handle properly. I suggest use `a?: Ref` as short alias for `a: Ref | null = null`. WDYT?

**Comment by dcodeIO** [comment]
Yeah, `i32 | null` should emit at least a warning. Can take a look at that later.

**Comment by MaxGraey** [comment]
But may be `Foo | null | null` issue better fix in separate PR.

**Pull request merged**
