### PR TITLE
fix: pre-analysis extendType before infer generic

### LINKED ISSUE #2405: Empty arrays as inputs with omitted default context loose this context for some reason
Simple example:
```ts
class A<T> {
  foo<U extends ArrayLike<T> = Array<T>>(a: U): U {
    return a;
  }
}

const a = new A<string>();
const r = a.foo([]); // `r` should infer as Array<string> but it `Array<usize>` instead
// a.foo<string[]>([]) // <- works

export function check(): bool {
  return r instanceof Array<string>;
}
```
AssemblyScript has a pessimistic rule. When empty array literal can't be inferred value type it presents this as `usize` instead `any` (TS-way). But this is not that situation.

### PR DESCRIPTION
**Pull request by HerrCai0907**
fix #2405 

concept of this PR is when inferring generic, use `extendType` as default type. And then use this default type to resolver argument type and get `targetType`. And then use `targetType` as `ctxType` to resolve argument expression.

For most of `resolveExpression`, `ctxType` do not have any effect, but for expression like `[]`, `ctxType` is effective

### CODE REVIEW

**Comment by HerrCai0907** [comment]
check `!extendTypeName.startsWith("ArrayLike") && extendTypeName != "number"` is a dirty work around solution to pass the test because std use lots of code like `extend ArrayLike` and `extend number`. I wonder how to handle it? update std or use more elegant way to avoid it.

**Comment by MaxGraey** [comment]
I guess it should be generalize to something like `!extendTypeName.isBuiltin()`

**Comment by MaxGraey** [comment]
Perhaps `extendType.isClass()` instead of these work arounds. @dcodeIO wdyt?

**Comment by dcodeIO** [comment]
Looking at the corresponding issue, the `extends ArrayLike<T>` doesn't seem to be relevant, but only the `= Array<T>` as the default type, i.e. this should work for `foo<U = Array<T>>(a: U): U` regardless of extendsType (which we currently simply skip)?

**Pull request closed without merging**
