### PR TITLE
Improve opt passes again

### PR DESCRIPTION
**Pull request by MaxGraey**
This also speed-up passing tests

### CODE REVIEW

**Comment by dcodeIO** [comment]
Would be great to have even more comments around there as it's hard to tell what's going on, and why, and in the exact order. Worrying that we'll otherwise accumulate pass-bloat, forgetting why specific passes are at the location they are, becoming impossible to reason about questions like "do we actually need to run this pass here?".

```
// now that stuff-X has been reduced by pass-X we can optimize the resulting stuff-Y with pass-Y, doing explain-Y
add("Y");
```

**Comment by MaxGraey** [comment]
Sure. I will try to describe all my steps, but it not always logical, sometimes just empirical find outs.

Btw I'm wondering is SSA used for globals? I guess it could optimize much more. See this for example:
https://github.com/AssemblyScript/assemblyscript/blob/6326ddf95408ac62775b24f7328c51235263d758/tests/compiler/logical.optimized.wat

**Comment by dcodeIO** [comment]
Afaik `(global ..)` optimizations are relatively basic, limited to detecting single uses that are never reassigned and such. Especially C/C++ don't emit a lot of globals, so I guess it hasn't been a high priority.

**Comment by dcodeIO** [comment]
In https://github.com/AssemblyScript/assemblyscript/pull/1046/commits/005dfbcf70e2ddeb297afd18754a30791c4fd7b9 I rebuilt the allocator tests and noticed that though the untouched fixtures became a bit smaller, the optimized ones became larger. May this have something to do with pass order or is this unrelated?

**Comment by MaxGraey** [comment]
`tests/allocators` don't update pretty often. See for example latest changes:
```wat
  (type $FUNCSIG$iii (func (param i32 i32) (result i32)))
  (type $FUNCSIG$ii (func (param i32) (result i32)))
```

to
```wat
 (type $i32_=>_none (func (param i32)))
 (type $none_=>_none (func))
```
and that's version don't contain `maybeGrowMemory` for example and other extra code which happened during long period

**Comment by MaxGraey** [comment]
@dcodeIO btw I updated that's tests in [this PR](https://github.com/AssemblyScript/assemblyscript/pull/1045) as well and it significant reduce sizes:
https://github.com/AssemblyScript/assemblyscript/pull/1045/files#diff-c18c517ac7bd11043db66de8d39266de

**Pull request merged**
