### PR TITLE
Refactor binary expression compilation to be reusable in builtins

### PR DESCRIPTION
**Pull request by dcodeIO**
In https://github.com/AssemblyScript/assemblyscript/pull/1484 it became apparent that we can share the code the compiler uses when compiling binary expressions, including taking care of SMI wrapping, during implementation of https://github.com/AssemblyScript/assemblyscript/issues/1310, so this refactors just making the IR out of `compileBinaryExpression`.

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by MaxGraey** [comment]
Could you add also shl, shr_s and shr_u unifications/builtins plz? It required for #1495

**Comment by dcodeIO** [comment]
I think the `make` helpers should be there now, with the builtins still to do. Does the linked issue require the builtins as well?

**Comment by MaxGraey** [comment]
I guess we should have built-ins for of all kind of bin operations?

**Comment by dcodeIO** [comment]
Agree, yes, just wondering whether these can be follow-up PRs :)

**Comment by MaxGraey** [comment]
Yeah, just mentioned this but if it will be another pr it will be fine as well)

**Pull request merged**
