### PR TITLE
Allow using a custom analyzer

### PR DESCRIPTION
**Pull request by singpolyma-shopify**
Export ExportsWalker to allow building custom walkers for analysis tools.

Allow an option to asc.main to get called with the Program object to
facilitate building custom CLIs on top of asc that call their own analysis
logic.

### CODE REVIEW

**Comment by dcodeIO** [comment]
This seems like it could reuse the existing `afterCompile` [transform](https://github.com/AssemblyScript/assemblyscript/tree/master/examples/transform), so exposing the walker would be sufficient.

**Comment by singpolyma-shopify** [comment]
@dcodeIO that transform looks like it gives access to a `Module` but I'm not sure I can get the `Program` from there in order to run a walker?  Maybe I'm just missing it.

**Comment by MaxGraey** [comment]
If you need program better use `afterParse` hook:
```ts
afterParse(parser: Parser) {
  const program = parser.program;
  ...
}
```
or you could save `program` reference and use it in `afterCompile` later

**Comment by singpolyma-shopify** [comment]
@MaxGraey thanks, I have it working using that strategy (save program reference from afterParse, then use in afterCompile).

So just the export, then.

**Comment by dcodeIO** [comment]
Alright, thanks! Maybe a word of caution: `ExportsWalker` is responsible for generating definitions, which hasn't been tested a lot. Might or might not work as expected, so if there are any issues, let us know :)

**Pull request merged**
