### PR TITLE
Revert Math.hypot tests

### PR DESCRIPTION
**Pull request by MaxGraey**
Since NodeJs 13 based on v8 8.7 we could try revert this tests

### CODE REVIEW

**Comment by dcodeIO** [comment]
Looks like tests currently run against v12 LTS and v13 stable, hence still failing for LTS.

**Comment by MaxGraey** [comment]
Yes. I guess best solution is detecting NODE version and expose this number to AS tests and later use conditional compilation

**Comment by dcodeIO** [comment]
While exposing the version can be done, that'd also mean different fixtures based on the respective node version. Not sure if worth. Maybe a config option in the respective test json indicating the minimum version of node?

**Comment by MaxGraey** [comment]
Another option - tell nvm install lts version before buggy `Math.hypot`

**Pull request closed without merging**
