### PR TITLE
Refactor pass pipline in cli

### PR DESCRIPTION
**Pull request by MaxGraey**
`converge` with `runPasses` may break some workflow like `--asyncify`. So in this PR I propose do following:
- Handle `asyncify` pass later and only once

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by dcodeIO** [comment]
What might be useful here is a way to let some passes run *before*  and others *after*. For asyncify in particular, instrumenting the module *before* and optimizing it with instrumentation now in place seems the most useful, though, while other passes might want to operate on the final output.

**Comment by MaxGraey** [comment]
I prefer don't breaking changes, so I just exclude `asyncify` and handle it in separate way

**Comment by dcodeIO** [comment]
A bit skeptical of attempting to work around this implicitly, though, as it will only work for asyncify, and only if it indeed is intended to run it before. Ideally, it seems we'd want `--runPassesBefore`, `--runPasses` (keeping it as-is) and `--runPassesAfter`, where the before and after passes are not part of converge?

**Comment by MaxGraey** [comment]
But how this resolve issue with `asyncify` with `converge`? For example we still need to handle `asyncify` as special pass which should include only in `runPassesAfter` but not in `runPassesBefore` or `runPasses`

**Comment by dcodeIO** [comment]
I'd expect that asyncify is a before-pass, as it instruments the module before it is optimized. Doing so will also optimize the asyncify code, which iiuc is quite important to reduce overhead.

**Comment by MaxGraey** [comment]
Asyncify should be run last and only once. Otherwise, other passes like inlining my break it

**Comment by dcodeIO** [comment]
Do you know where the code for running Asyncify is in Binaryen? I guess I should take a look :)

**Comment by MaxGraey** [comment]
Asyncify usually run as separate individual pass. See this example: https://github.com/GoogleChromeLabs/asyncify#webassembly-side. Btw `asyncify` also accept input arguments

**Comment by dcodeIO** [comment]
Hmm, if it's that complicated, I am probably fine with doing the right thing implicitly. Should running asyncify also disable inlining then? Alternatively, this could not be a pass but an `--asyncify` option, I guess, then modifying the pipeline for asyncify?

**Comment by MaxGraey** [comment]
Yeah, I guess better move `asyncify` out from usual passes as separate option

**Comment by MaxGraey** [comment]
Btw it has different args "blacklinst", "addlist", "ignorelist" and erc:
https://github.com/WebAssembly/binaryen/blob/main/test/lit/passes/asyncify_pass-arg=asyncify-addlist@foo_pass-arg=asyncify-ignore-indirect.wast#L4

**Comment by dcodeIO** [comment]
If there was an `--asyncify` option, it could perhaps take the arguments as a list, say `addlist=...,ignorelist=...`.

**Pull request closed without merging**
