### PR TITLE
Add heap2local to pass pipeline

### PR DESCRIPTION
**Pull request by MaxGraey**
This version fix [compiler's speed regression](https://github.com/WebAssembly/binaryen/issues/3857)

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by dcodeIO** [comment]
The package-lock changes are really unfortunate :)

**Comment by MaxGraey** [comment]
It just change stuffs related to binaryen

**Comment by dcodeIO** [comment]
Oh, I see now, these are fixtures. Heh, look how paranoid I have become about updating dependencies across OSes already :)

**Comment by dcodeIO** [comment]
I guess we could also wait with this until I update the SIMD PR, which will need a new Binaryen version anyhow.

**Pull request merged**
