### PR TITLE
feat: Introduce new parse methods for builtin value types. Deprecate XX.parseInt/parseFloat

### PR DESCRIPTION
**Pull request by MaxGraey**
New static methods:
```ts
u8.parse
i8.parse
u16.parse
i16.parse
u32.parse
i32.parse
u64.parse
i64.parse

f32.parse
f64.parse

bool.parse
```
Deprecated:
```ts
U8.parseInt
I8.parseInt
U16.parseInt
I16.parseInt
U32.parseInt
I32.parseInt
U64.parseInt
I64.parseInt

F32.parseInt
F64.parseInt
F32.parseFloat
F64.parseFloat
```

**Motivation**

`U8.parseInt` and `F32.parseInt` / `F32.parseFloat` are a tracing of `Number.parseFloat` and `Number.parseInt` which makes sense in JS due to we have on Number and can't distinguish from int and float.

In AssemblyScript we have a completely different story. So I propose to declare these methods obsolete and use simpler and clearer names for parsing instead.

It is also good correlated with `Date.parse`, `Temporal.parse` and `JSON.parse`

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by dcodeIO** [comment]
To summarize what we have talked about, I think we should keep non-standard additions on the respective lowercase namespaces, here `f32` etc., where similar additions are already present. Then we'd have a non-standard `f32.parse` for example, which can freely provide such additions, plus standards-aligned (that is: as of the `Number` class in JS) functionality on `F32` etc. (which all mimic `Number` but per concrete Wasm type). A follow-up could be to add a `@deprecated("some message")` decorator on the `F32.xy` APIs that prints a message hinting at `f32.parse` being the better API.

**Comment by MaxGraey** [comment]
Yes, I added non-standard "parse" methods only for lowercase types. At the moment, the "@deprecated" decorator is used. We can add a more specialized deprecated decorator from our side in the future.

**Comment by trusktr** [comment]
`Number.parseFloat` and `Number.parseInt` are about string types being parsed, not about the output number type.

**Comment by MaxGraey** [comment]
`Number.parseFloat` and `Number.parseInt` didn't remove. Just deprecated for AS only usage. Portability is a different story. If you want a portable code, you can still use these methods

**Comment by trusktr** [comment]
Oh, got it. I overlooked.

**Comment by MaxGraey** [comment]
Also note `this.parseFloat === Number.parseFloat` and `this.parseInt === Number.parseInt`. It's just aliases introduced in ES2016 for better modularize. So you can just use `parseFloat` / `parseInt` is you want to suppress a deprecated warns in editor

**Pull request merged**
