### PR TITLE
Fix realloc alignment and use before initialization

### PR DESCRIPTION
**Pull request by dcodeIO**
As discovered in https://github.com/AssemblyScript/assemblyscript/issues/1023 there is an issue with `__realloc` when using the stub runtime and reallocation of static memory is performed. While investigating I spotted several problems:

* Static segments still used an alignment of 8 instead of 16 bytes as we require nowadays. Changed that to 16.
* The stub runtime has some debug-only asserts that looked for `RC=-1` meant to indicate that there's no GC here, but static segments are created with `RC=1` targeting the full runtime. So stub now uses `RC=1` as well.
* The full runtime did not account for the case that `__realloc` can be called with static memory before initialization has been performed.

fixes https://github.com/AssemblyScript/assemblyscript/issues/1023

### CODE REVIEW

**Comment by vladimir-tikhonov** [comment]
Thanks for having a look, @dcodeIO! Unfortunately, this doesn't seem to help much for optimized builds. One thing I've noticed is that this code
```typescript
let initializedArray: i32[] = [];
initializedArray = [];
```
Produces a wasm file with a `func $start:assembly/index` which calls `~lib/rt/__allocArray` and stuff, while just
```typescript
let initializedArray: i32[] = [];
```
doesn't have any `$start` method at all

**Comment by dcodeIO** [comment]
When the compiler sees an array literal, it first attempts to make a static memory segment of it. I guess that's what you are seeing there.

```ts
export let initializedArray: i32[] = [];
```

becomes static memory while

```ts
initializedArray = [];
```

actually allocates.

**Comment by MaxGraey** [comment]
And I guess workaround:
```ts
export let initializedArray = new Array<i32>();
```

**Comment by dcodeIO** [comment]
So, is there still an issue with this, like hitting a trap somewhere?

**Comment by vladimir-tikhonov** [comment]
@dcodeIO, yep, what I was trying to say is that the code example from #1023 

```typescript
const initializedArray: i32[] = [];

export function willFail( value: i32 ): void {
    initializedArray.push( value );
}
```
will fail in runtime even with the changes from this pull request (actually in the very same place)

**Comment by vladimir-tikhonov** [comment]
> And I guess workaround if you force alloc in heap

Unfortunately that doesn't really work for me. That issue is all around my codebase, I've got similar errors when trying to create an instance of an unmanaged object during initialization (and I do create a lot of them :)). Actually it may be another non-related issue but I will rather wait for a fix for #1023 and re-check if anything's still broken

**Comment by vladimir-tikhonov** [comment]
Upd: just to be exactly clear - `willFail` should be actually called from js in order to get an exception

**Comment by dcodeIO** [comment]
Can confirm, I apparently fixed this for stub/none but there's another problem with full/half.

**Comment by dcodeIO** [comment]
Updated the opening post accordingly. Let me know if the problem disappeared :)

**Comment by vladimir-tikhonov** [comment]
@dcodeIO yep it works, thank you! I'm hitting another `assert` in `allocateBlock` now, but it seems unrelated and I will create another issue.

**Pull request merged**
