### PR TITLE
Improve inferring generic parameters

### PR DESCRIPTION
**Pull request by dcodeIO**
potentially fixes https://github.com/AssemblyScript/assemblyscript/issues/219
potentially fixes https://github.com/AssemblyScript/assemblyscript/issues/837

This makes use of the new resolver infrastructure to improve inferring generic types, like in

```ts
function test<T>(arr: T[]) { ... }
test(float32Array);
// resolving Array<f32>, inferring T = f32
```

```ts
function test<T,R>(fn: (a: T) => R) { ... }
test(someFunctionTakingF32ReturningF64);
// resolving (a: f32) => f64, inferring T = f32, R = f64
```

by first obtaining the type of the respective argument containing a type parameter and then matching it, including encapsulated type parameters, against the template.

Still feels a bit fragile as if I'd missed something, so if you spot an issue, let me know :)

### CODE REVIEW

**Comment by dcodeIO** [comment]
The other issue should be resolved as well with the last commit. Now infers all types first while updating to compatible types, and only then does another pass to do the actual resolving.

**Comment by MaxGraey** [comment]
It will be great inferring type from argument as well. For example:
Current (with this PR as well):
```ts
arr.reduce<i32>(((prev: i32, current: i32): i32 => prev + current), 0); // but `0` already infer as `i32`
```
Will be great don't specify `<i32>` for `T` and infer it from last argument like:
```ts
arr.reduce(((prev: i32, current: i32): i32 => prev + current), 0);
```

**Comment by dcodeIO** [comment]
Last commit should fix issues with

```ts
arr.reduce(((prev: i32, current: i32): i32 => prev + current), 0);
```

inferring `U <- i32` but it doesn't look like

```ts
arr.reduce(((prev, current) => prev && current), false);
```

can be supported since `U` cannot be derived from anything in this case.

**Comment by dcodeIO** [comment]
Wait,

```ts
arr.reduce(((prev, current) => prev && current != 0), false);
```

appears to compile now. I guess the other logic we have for function expressions without types can pick this up now since the code now uses `compileCallExpression`.

**Comment by MaxGraey** [comment]
Great!

**Pull request merged**
