### PR TITLE
feat: implement scoped type alias

### PR DESCRIPTION
**Pull request by HerrCai0907**
use `Flow` to store scoped type alias and lookup it when resolve `NamedType`.

### CODE REVIEW

**Comment by MaxGraey** [comment]
Does it support `type Elem = valueof<Array<T>>`? It will be great to reduce verbosity for [this method](https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/typedarray.ts#L1910)

**Comment by HerrCai0907** [comment]
> Does it support `type Elem = valueof<T>`? It will be great to reduce verbosity for [this method](https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/typedarray.ts#L1910)

Yes.
The output of these code would be
```ts
function foo<T extends ArrayLike<number>>(): void {
  type Elem = valueof<T>;
  trace(nameof<Elem>());
}

export function _start(): void {
  foo<i32[]>();
  foo<u32[]>();
  foo<string[]>();
}
```
```
i32
u32
String
```

**Review by CountBleck — APPROVED** [review]
Beautiful. I'd guess this doesn't work for:
```ts
function foo(): void {
    let baz: Bar = []; // Bar needs to be hoisted
    type Bar = Array<i32>;
}
```

Still, almost no one depends on that detail, so this is practically ready to merge (unless I've missed something).

**Comment by HerrCai0907** [comment]
> Beautiful. I'd guess this doesn't work for:
> 
> ```ts
> function foo(): void {
>     let baz: Bar = []; // Bar needs to be hoisted
>     type Bar = Array<i32>;
> }
> ```
> 
> Still, almost no one depends on that detail, so this is practically ready to merge (unless I've missed something).

Yes. It is a huge feature we cannot fulfill at this moment. TS can do definition after usage. Actually I don't like to this design. Maybe we can add something like "scope analysis` to detect and diagnose it.

**Comment by CountBleck** [comment]
It's not a big deal. This is good as-is.

**Pull request merged**
