### PR TITLE
Respect absolute output paths

### LINKED ISSUE #1215: asc does not respect absolute output paths
```
$ asc src/perlin.ts --sourceMap -b /tmp/perlin.wasm
```

This ends up creating a `tmp` folder in `$PWD`, when it should just use the existing `/tmp` folder.

Version: 0.9.4

### PR DESCRIPTION
**Pull request by surma**
I wanted to test #1216, but it turned out it was a bit more complicated. Thought I’d get my hands dirty rather than stretching this out any further. Hope you don’t mind, @MaxGraey.

Fixes #1215

### CODE REVIEW

**Comment by MaxGraey** [comment]
You should add yourself to [NOTICE file](https://github.com/AssemblyScript/assemblyscript/blob/master/NOTICE#L23)

**Comment by dcodeIO** [comment]
Guess who immediately anticipated having to fix CI again

**Comment by surma** [comment]
:sweat_smile: done

**Comment by surma** [comment]
Looking forward to make lawsuits part of my regular schedule.

**Pull request merged**
