### PR TITLE
Update to latest Binaryen & introduce anyref

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR moves us to the bleeding edge again by integrating new shiny Binaryen features. In particular:

* Preliminary support for `anyref` as an opague type behind the `--enable reference-types` flag. <del>Still misses checks all over the place to distinguish between an internal (integer) reference and an external (anyref) reference, but</del> passes a simple test for declaring `anyref` parameters and return types and passing them around. Don't get too excited yet.

* The `atomic.fence` instruction

* Various flags for features the compiler doesn't utilize yet, like nontrapping float to int, exception handling and tail calls.

* Bindings for the `try`, `throw`, `rethrow`, `br_on_exn` family of instructions.

* Event API to declare exception events.

* Bindings for the `push` and `pop` instructions.

* Bindings for the `return_call` and `return_call_indirect` instructions.

* Bindings for the new qfma/qfms SIMD instructions.

* Proper ids of the nontrapping float to int instructions.

* Some early bindings for `Reflect` and `console` to showcase the concept of working with `anyref`.

* A mechanism to run code pre and post instantiation in tests, e.g. to populate imports

* Updated tests for the various feature flags

### CODE REVIEW

**Comment by dcodeIO** [comment]
The [respective test case](https://github.com/AssemblyScript/assemblyscript/blob/update-binaryen2/tests/compiler/anyref.ts) now also showcases a bit how working with `anyref` does work. As far as I can tell we are still missing the `ref.null` instruction, but we can already import a `null` and an `undefined` anyref manually to make things work.

**Comment by jtenner** [comment]
What a time to be alive!

**Comment by MaxGraey** [comment]
Hey. It seems this more complex PR than just update binaryen. Probably better rename it? And also create another PR with updated to latest binaryen and new dist files because WebAssembly Studio currently broken

**Comment by MaxGraey** [comment]
I guess TODO point could be already checked)

**Comment by MaxGraey** [comment]
wdyt bump version to `0.8.0`?

**Comment by MaxGraey** [comment]
> wdyt bump version to 0.8.0?

After merge this PR, sin/cos, improved `parseFloat` and fix for module resolver

**Comment by dcodeIO** [comment]
> wdyt bump version to 0.8.0 after merge this PR, sin/cos, improved parseFloat and fix for module resolver

Sure, why not.

This PR should be good now even with https://github.com/WebAssembly/binaryen/pull/2336 not yet landed (utilizes a constant as a workaround until then).

**Pull request merged**
