### PR TITLE
Infer function expressions in matching contexts

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR

1. legalizes omitting types on function expressions within function type contexts and
2. legalizes omitting any number of arguments

As an example, the test looks like this:

```ts
function testOmitted(fn: (a: i32, b: i32) => i32): i32 {
  return fn(1, 2);
}
assert(testOmitted((a, b) => a + b) == 3);
assert(testOmitted(a => a) == 1);
assert(testOmitted(() => 42) == 42);

function testOmittedReturn1(): (a: i32, b: i32) => i32 {
  return (a, b) => a + b;
}
function testOmittedReturn2(): (a: i32, b: i32) => i32 {
  return a => a;
}
function testOmittedReturn3(): (a: i32, b: i32) => i32 {
  return () => 42
}
assert(testOmittedReturn1()(1, 2) == 3);
assert(testOmittedReturn2()(1, 2) == 1);
assert(testOmittedReturn3()(1, 2) == 42);

```

fixes https://github.com/AssemblyScript/assemblyscript/issues/449

### CODE REVIEW

**Comment by dcodeIO** [comment]
One remaining question is whether we should more strictly check the signature, i.e. changing

```ts
map<U>(callbackfn: (value: T, index: i32, array: Array<T>) => U): Array<U>
```

etc. into

```ts
map<U>(callbackfn: (value: T, index?: i32, array?: Array<T>) => U): Array<U>
```

etc. and, in this example, requireing at least one parameter to be present, even though, technically, any number of parameters less than max works as long as the return type matches. Wdyt?

**Comment by MaxGraey** [comment]
Hmm, I don't think this make sense. Usually all params in signatures like that should be always optional by default. So add manual optional mark `?` is unnecessary work I think.

**Comment by dcodeIO** [comment]
Right, looks like the only place where the signature actually matters is where it is actually called (here: fn() inside of map). Let's do it the TS way then.

**Comment by MaxGraey** [comment]
fully optional map's call back signature also possible in real scenario: `arr.map(() => 0)` (just got zero filled array with same length of `arr`)

**Pull request merged**
