### PR TITLE
[Ignore this] Speedup n-body optimize experiment

### PR DESCRIPTION
**Pull request by MaxGraey**
This changes provide speedup n-body bench by ~10%. Create just for research purposes.

**before**:
```
Performing 20000000 steps (WASM)
Took 3751ms
Performing 20000000 steps (JS)
Took 2711ms
```

**EDITED**
**latest progress**
```
Performing 20000000 steps (WASM)
Took 2591ms
Performing 20000000 steps (JS)
Took 2637 ms
```

### CODE REVIEW

**Comment by dcodeIO** [comment]
To summarize, this is due to the additional indirection introduced by backing `Array<T>` with an `ArrayBuffer`, which is necessary because the data can grow (implies that the pointer to it can change) while the pointer to the instance must remain the same. A manual optimization like this works because data actually doesn't grow in this case and it is guaranteed that the data pointer is constant for the entire loop, means that an automatic optimization would have to know that this condition applies as well so it can do a similar substitution (pull a local from out of the loop and reuse it) automatically.

To generalize, this is similar to

```ts
for (let i = 0; i < a.len; ++i) {
  log(a.len);
}
```

where `a.len` becomes an `i32.load` but could be substituted with a `get_local` (possibly becoming a register operation in native code) as long as it is known to remain constant over a set of operations. Adding one level of indirection to it leads us to the proposed optimization.

My feeling is that a more general optimization would be the ideal solution here because there's more to it than just indexed access (i.e., also affects any use of `this.someProperty` which could be cached in a local when used multiple times), but might be quite complicated to do because a compiler/optimizer would have to keep track of memory that doesn't respectively does change. LLVM probably has something to do this. @kripken ?

**Comment by kripken** [comment]
If I understand properly, what happens here is that one `load` is moved out of the inner loop, and that's the cause of the speedup? And this is done by something metaphorically like
```
for (let i = 0; i < a.len; ++i) {
  log(a.len);
}
==>
var len = a.len;
for (let i = 0; i < len; ++i) {
  log(len);
}
```
?

If so, then optimizing this in general is not easy. The inner loop has a store, so the optimizer needs to be smart enough to know that that store will not affect that load, that is, that they don't alias. In LLVM alias analysis can happen if the load is of one type and the store of another, which is undefined behavior in C. In wasm, though, there is no undefined behavior like that. So we'd need to actually have a smart enough optimizer to prove that manually, that is, somehow show that the range of possible memory regions modified by the store does not overlap at all with the range of regions read by the load. That would be quite hard.

Note btw that in JS this is also easier than in wasm, even easier than in C, since `a.len` is a load from the object `a`, so if nothing else accesses `a`, it is guaranteed to not alias (which is easy to prove in the example here).

**Comment by MaxGraey** [comment]
@kripken @dcodeIO Not certainly in that way. Optimization consist of two tweaks. First is caching and move out of loop internal buffer pointer which could change when array growing like `Array#push` or `Array#length = someNewNum`. But in current situation we have "static/fixedsized array" also this could be easy determine and apply for `TypedArrays` which have always fixed size. This tweak improve example by ~12-15%.
Second tweak is avoid using computed multiplication during addressing in `load` which possible because we use `load` operation inside loop and change `load<T>(ptr + index * const, 8)` to `load<T>(ptr + offset, 8), offset += const`. This improvements gives us +10-13% more boost. So in total we get 25% boost.

```

**Comment by MaxGraey** [comment]
@kripken I should emphasize second part because it potentially could optimize by binaryen. Main reason why we should avoid multiplication in that case because jit can't properly do this in fast way. Actually it could do this if `const` is POT (power of two constant). For example:
```ts
export function accessPOT(ptr: usize, index: usize): i32 {
  return load<i32>(ptr + 4 * index, 8); // 4 is POT
}
```
output asm by Mozilla:
```asm
  lea eax, dword ptr [rdi + rsi * 4]
  mov eax, dword ptr [r15 + rax + 8]
```
Which is not the best but acceptable. Now look at the case when `const` is not POT (which we actually have in n-body example):
```ts
export function accessNotPOT(ptr: usize, index: usize): i32 {
  return load<i32>(ptr + 5 * index, 8);
}
```
output:
```asm
  imul esi, esi, 5
  add esi, edi
  mov eax, dword ptr [r15 + rsi + 8]
```
As we see have `imul + add + mov` instead `lea + mov` which much slower. That's because `mov` has some limit rules during address arithmetic. Actually first case (with POT) good compilers like LLVM and GCC could optimize to something like `mov  eax, DWORD PTR [rdi + rsi * 4 + 8]`.

**Comment by MaxGraey** [comment]
ok, I found bug and figure outing what my last assumption is wrong and not significant influence on perf (I mean POT-nonPOT indexation).

Correct results:
**before**
```
Performing 20000000 steps (WASM)
Took 3751 ms
Performing 20000000 steps (JS)
Took 2711 ms
```
**after**
```
Performing 20000000 steps (WASM)
Took 3493 ms
Performing 20000000 steps (JS)
Took 2686 ms
```

**Comment by MaxGraey** [comment]
But current mozilla's VM definitely could be improve POT access and use
```
mov eax, dword ptr [rdi + rsi * 4 + 8]
```
instead
```
lea eax, dword ptr [rdi + rsi * 4]
mov eax, dword ptr [r15 + rax + 8]
```

**Comment by MaxGraey** [comment]
Finally wasm is pretty close to JS but with some hints which made it unsafe =(

**before**
- AssemblyScript WASM 
3343.628437ms
- JS 
2677.931158ms
- Rust WASM  
3766.934673ms

**after**
- **AssemblyScript WASM**
**2820.178382ms**
- JS 
2732.275025ms
- Rust WASM 
2920.7042659999997ms

**Comment by dcodeIO** [comment]
Interesting results nonetheless! So, is it safe to say that there's still quite some headroom in other moving parts that are not directly under our control, and there's only so much we can do when generating the actual binary?

**Comment by MaxGraey** [comment]
Yeah. But improvements should occur from AS (loop invariant code motion for backed buffer) and wasm vm. Currently most significant boost give me `--wasm-no-bounds-checks` flag for v8. Also latest version of v8 support "loop rotation optimization" but latest node 11.9 doesn't support this yet. So I expect even more speedup in near future

**Comment by MaxGraey** [comment]
New stats for v11.10.0:

**before**

    - **AssemblyScript WASM**
      **2820.178382ms**

    - JS
      2732.275025ms

    - Rust WASM
      2920.7042659999997ms

**after**

    - **AssemblyScript WASM**
      **2796.586051ms**

    - JS
      2743.860923ms

    - Rust WASM
      2976.888013ms

**Comment by MaxGraey** [comment]
**before (v11.10.0)**

  - AssemblyScript WASM
    2796.586051ms
  - JS
    2743.860923ms
  - Rust WASM
    2976.888013ms

**after (v11.10.1)**

  - AssemblyScript WASM
    2728ms
  - JS
    2645ms
  - Rust WASM
    2796ms

**Comment by MaxGraey** [comment]
**node v11.12.0**

- **AssemblyScript WASM**
  **2760ms**
- JS
  2678ms
- Rust WASM
  2853ms

**Comment by MaxGraey** [comment]
**node (v12.4.0)**

- **AssemblyScript WASM**
  **2591.955497ms**
- AssemblyScript ASMJS
  3821.713045ms
- JavaScript
  2637.882871ms
- Rust WASM
  2668.269144ms

Finally with additional `--wasm-no-stack-checks` flag AS outperform n-body over JS

**Comment by MaxGraey** [comment]
**node v12.10.0**

- AssemblyScript 
`2551.9ms`
- JS 
`2640.4ms`
- Rust WASM 
`2613.4ms`

**Comment by MaxGraey** [comment]
**node v12.10.0** + latest Rust

- AssemblyScript
    `2642.9ms`
- JS
    `2717.7ms`
- Rust WASM
    `2559.6ms`

**Pull request closed without merging**
