### PR TITLE
Print better errors for unusual void, null and undefined types

### PR DESCRIPTION
**Pull request by dcodeIO**
Fixes https://github.com/AssemblyScript/assemblyscript/issues/558 by making

```ts
export function test1(x: void): void {}

export function test2(x: undefined): void {}

export function test3(x: null): void {}

export function test4(a: string | undefined): void {}
```

now diagnosing

```
ERROR TS1110: Type expected.

export function test1(x: void): void {}
                         ~~~~
in input.ts(1,26)
```

```
ERROR TS2304: Cannot find name 'undefined'.

export function test2(x: undefined): void {}
                         ~~~~~~~~~
in input.ts(3,26)
```

```
ERROR TS2304: Cannot find name 'null'.

export function test3(x: null): void {}
                         ~~~~
in input.ts(5,26)
```

```
ERROR TS1005: 'null' expected.

export function test4(a: string | undefined): void {}
                                  ~~~~~~~~~
in input.ts(7,35)
```

with `test4` diagnosed early on parser level.

### CODE REVIEW

**Comment by MaxGraey** [comment]
Could it also handle this case?
```
let x: void;
let y = <void>1;
let z: undefined;
let w = <undefined>1;
```

**Comment by dcodeIO** [comment]
The new given examples diagnose

```ts
let x: void; // TS1110: Type expected.
let y = <void>1; // TS2322: Type 'void' is not assignable to type '<auto>'.
let z: undefined; // TS2304: Cannot find name 'undefined'.
let w = <undefined>1; // TS2304: Cannot find name 'undefined'.
```

while a `void | something` return type seems to exit early on `void`, leading to `TS2391: Function implementation is missing or not immediately following the declaration` kind of errors. Going to see if I can do something about these as well.

**Comment by dcodeIO** [comment]
Last commit changes the parsing of union return types to always occur, so

```ts
export function test6(a: string): void | null {}
```

now diagnoses

```
ERROR AS204: Basic type 'void' cannot be nullable.

export function test6(a: string): void | null {}
                                  ~~~~
in empty.ts(1,35)
```

**Comment by MaxGraey** [comment]
Great! Well done!

**Pull request merged**
