### PR TITLE
Add sealed decorator for Map, Set and Array

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Array, Map and Set (unlike String and ArrayBuffer that do exotic things with their memory) should be safe to extend. Or is there another reason for sealing them?

**Comment by MaxGraey** [comment]
As I know Typescript same as plain Javascript not allow extending buildin types. Only babel has workaround [for this](https://github.com/babel/babel/pull/7020). But may be in AS it makes sense in view of the fact that there is no other way like dynamic add methods to prototype.

**Comment by xtuc** [comment]
ES2015 classes (plain JavaScript) allows extending built-ins. Babel couldn't allow that for a long time but it will eventually be fixed in the next major version. 

I would assume that TypeScript follows the spec in that regards and allow extending built-in but I'm not sure.

**Comment by MaxGraey** [comment]
Thanks xtuc. You are right. In view of the problem with this in **babel**, I thought this restriction whole for JS =) In that case, I close PR

**Pull request closed without merging**
