### PR TITLE
Cast to bool by comparing to zero

### PR DESCRIPTION
**Pull request by dcodeIO**
See: https://github.com/AssemblyScript/assemblyscript/issues/342

### CODE REVIEW

**Comment by MaxGraey** [comment]
btw, why binaryen use `i32.ne`/`i64.ne` with zero constant instead just one opcode `i32.eqz`/`i64.eqz`?

**Comment by dcodeIO** [comment]
eqz checks for "== 0" while we need "!= 0". When optimizing, Binaryen converts to eqz if the surrounding code allows it, i.e. double negate.

**Comment by MaxGraey** [comment]
I mean cases when we have `i32.ne` + `i32.eqz` which is actually `(x != 0) == 0` and could be simplify to `x == 0` (i32.eqz). [Like this](https://github.com/AssemblyScript/assemblyscript/pull/343/files#diff-b6d05bba9657839243d89be47194d27eR177)

**Comment by dcodeIO** [comment]
This seems to be from untouched output, which is expected (especially in combination with `assert` which is particularily odd). Should be better once optimized.

**Comment by MaxGraey** [comment]
I see. It seems binaryen even better optimize `!= 0` then `& 1`

**Pull request merged**
