### PR TITLE
Fix TypedArray.wrap definition

### PR DESCRIPTION
**Pull request by MaxGraey**
Relate to #938

### CODE REVIEW

**Comment by dcodeIO** [comment]
Considering that the implementation isn't generic, wouldn't it be straight-forward to model the declaration exactly like that by adding one `.wrap` to each subclass with a concrete return type? Would otherwise imagine that someone could try to use it as a generic function with unexpected results.

**Comment by MaxGraey** [comment]
I simplify this. I guess this completely solved issue

**Comment by MaxGraey** [comment]
> Considering that the implementation isn't generic, wouldn't it be straight-forward to model the declaration exactly like that by adding one .wrap to each subclass with a concrete return type? 

What about this?
```ts
static wrap<T = TypedArray<number>>(this: Ctor<T>, buffer: ArrayBuffer): T;
```

**Comment by dcodeIO** [comment]
That's ideal, thanks! :)

**Pull request merged**
