### PR TITLE
Add env:abort function stub for wasm's import in template for asinit script

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Maybe we can even go a bit further here and use the loader, so everyone has its functionality out of the box. Wdyt?

**Comment by MaxGraey** [comment]
I think better use some prompt and allow user to choose loader or existing simple boilerplate code.

**Comment by MaxGraey** [comment]
I worry when loader would include by default we lost status of glue-free wasm language =)

**Comment by dcodeIO** [comment]
Hmm. Chances are that someone using `asinit` the first time doesn't know an answer to this question yet. What if the the index file would have both `loader.instantiate` and `WebAssembly.instantiate`, with the loader being the default and the other being commented out, plus a short sentence what commenting out one and uncommenting the other does?

**Comment by MaxGraey** [comment]
Or just link to documentation for loader with more advanced examples

**Comment by MaxGraey** [comment]
Could we merge this as temporary solution?

**Comment by dcodeIO** [comment]
Sure :)

**Pull request merged**
