### PR TITLE
Add more numeric builtin methods

### PR DESCRIPTION
**Pull request by MaxGraey**
**TODO**

 - [x] Number.isNaN()
 - [x] Number.isFinite()
 - [x] Number.isSafeInteger()
 - [x] Number.isInteger()
 - [x] Number.parseInt()
 - [x] Number.parseFloat()

 - [x] basic tests
 - [x] more tests and definitions

### CODE REVIEW

**Comment by dcodeIO** [comment]
Looking good so far :)

**Comment by MaxGraey** [comment]
Now done!

**Comment by MaxGraey** [comment]
Now done! =)

**Comment by dcodeIO** [comment]
Thanks! :)

**Pull request merged**
