### PR TITLE
fix: Fix mixed up naming "upcast" <-> "downcast" for runtime checks

### PR DESCRIPTION
**Pull request by danaugrs**
Fixes https://github.com/AssemblyScript/assemblyscript/issues/2422.

### CODE REVIEW

**Comment by MaxGraey** [comment]
I'm little bit confused. Downcasting doesn't require runtime checking at all due it's could be proved in compile time while upcasting required that.

**Comment by JesseCodeBones** [comment]
I have no permission to edit, but I can tell you the root cause.
wat file will store the error message with utf8 format, as you changed the error message, you should change its wat as well.
postion: line 41 at `debug.wat`
new message: ` (data (i32.const 540) "<\00\00\00\00\00\00\00\00\00\00\00\01\00\00\00&\00\00\00u\00n\00e\00x\00p\00e\00c\00t\00e\00d\00 \00d\00o\00w\00n\00c\00a\00s\00t\00\00\00\00\00\00\00")`

position: line 37 at `release.wat`
new message: `(data (i32.const 1576) "\01\00\00\00\"\00\00\00u\00n\00e\00x\00p\00e\00c\00t\00e\00d\00 \00d\00o\00w\00n\00c\00a\00s\00t")`.

Good luck!

**Comment by MaxGraey** [comment]
Just recreate all fixtures via `ASC_FEATURES="*" npm run test:compiler -- --create` command to make sure

**Comment by danaugrs** [comment]
Updated, thanks for the help guys!

**Review by MaxGraey — APPROVED** [review]

**Comment by danaugrs** [comment]
@MaxGraey I don't have write access so I can't merge (just letting you know in case you are waiting for me to do so).

**Comment by MaxGraey** [comment]
@danaugrs We have an automatic release process (via github action) so we usually collect and merge a bunch of PRs at once. I'll begin the merging process soon

**Comment by MaxGraey** [comment]
Thanks!

**Pull request merged**
