### PR TITLE
Implement v128 instructions

### PR DESCRIPTION
**Pull request by dcodeIO**
**Edit:** This escalated and is complete now.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Hmm, it might actually be easier to defer `i64x2.splat` -> `v128.splat<i64>` in order to share most of the codegen here, quite similar to what we do with `i32.clz` -> `clz<i32>` etc.

**Comment by MaxGraey** [comment]
I'm not sure this convention apply to rest operations

**Comment by dcodeIO** [comment]
From the proposal [it seems](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md) that the name of the operation, i.e. `add`, plus a single type parameter, i.e. `<i64>` is sufficient to represent which instruction to pick when bound to the underlying vector type (here `v128`). One `v128` per `i64` gives us 2 lanes etc.

**Comment by MaxGraey** [comment]
yeah, it seems for fixed length SIMD operations this correct)

**Comment by MaxGraey** [comment]
@dcodeIO shuffling lanes operation could be also not trivial for "first good issue". wdyt?

**Comment by dcodeIO** [comment]
Looks like that's essentially just a v128,v128->v128 binary plus an additional lane index like in extract_lane/replace_lane. Should be straight forward :)

**Comment by MaxGraey** [comment]
Nope) It's `v128,v128,imm[16]->v128`. This instruction is encoded with 16 bytes providing the indices of the elements to return. The indices i in range [0, 15] select the i-th element of a. The indices in range [16, 31] select the i - 16-th element of b. `imm` is array of constants and compiler should check this

**Comment by dcodeIO** [comment]
I understand. Well, actually I don't, so I guess you're right :)

**Comment by dcodeIO** [comment]
Regarding shuffle it might also be convenient to provide typed versions like `i64x2.shuffle` as well (even though these are not in the spec), so `v8x16.shuffle` would essentially become an alias of `i8x16.shuffle` which itself would become a defered call to `v128.shuffle<T>`. Wdyt?

**Comment by MaxGraey** [comment]
What do you think about add `align` attribute for `load` and `store` intrinsics? I guess it may some meaning for SIMD's load/store

**Comment by dcodeIO** [comment]
For context: Currently all load/store ops use natural alignment, in the case of `v128` that's 16 bytes. Natural alignment isn't displayed in text format iiuc. I must admit though that I don't fully understand the full implications of the alignment hint, and it appears to me to be most useful when actually diverging from natural alignment?

**Comment by dcodeIO** [comment]
One strange thing about the alignment hint is that the spec speaks of "an alignment hint (in base 2 logarithmic representation)", while Binaryen's `CreateLoad` takes the size in bytes (which is fine) but the text format also outputs the size in bytes. Is this expected?

**Comment by MaxGraey** [comment]
May be better ask this to @kripken?

**Comment by dcodeIO** [comment]
The text format spec speaks of "The offset defaults to 0, the alignment to the storage size of the respective memory access", which somewhat indicates that, though the alignment is represented in log2 in binaries, it is represented in bytes in the text format?

**Comment by dcodeIO** [comment]
Looking at some test cases, it indeed seems that the alignment in text format is represented in bytes. [Example WABT test](https://github.com/WebAssembly/wabt/blob/c9d29f0a26bf2915288d8653258aa4fc89cc8d0f/test/parse/expr/load-aligned.txt#L6). Going to implement it this way now :)

**Comment by dcodeIO** [comment]
It's unfortunate that we can't actually run the tests on our normal setup, so eventual errors can't be easily caught. My feeling is that this restriction is going to get more problematic over time, and that we should try to make our test suite use bleeding edge v8 or something like that. How close can we get to something that just works and has all the latest Wasm features with something like [node-v8](https://github.com/nodejs/node-v8)? Any experience?

**Comment by dcodeIO** [comment]
Latest [nightly](https://nodejs.org/download/nightly/v12.0.0-nightly20190226ccd6b12fec/) shows this:

```
  --experimental-wasm-mv (enable prototype multi-value support for wasm)
        type: bool  default: false
  --experimental-wasm-eh (enable prototype exception handling opcodes for wasm)
        type: bool  default: false
  --experimental-wasm-se (enable prototype sign extension opcodes for wasm)
        type: bool  default: true
  --experimental-wasm-sat-f2i-conversions (enable prototype saturating float conversion opcodes for wasm)
        type: bool  default: false
  --experimental-wasm-threads (enable prototype thread opcodes for wasm)
        type: bool  default: false
  --experimental-wasm-simd (enable prototype SIMD opcodes for wasm)
        type: bool  default: false
  --experimental-wasm-anyref (enable prototype anyref opcodes for wasm)
        type: bool  default: false
  --experimental-wasm-mut-global (enable prototype import/export mutable global support for wasm)
        type: bool  default: true
```

**Comment by MaxGraey** [comment]
Hmm, that's pretty full post-MVP feature sets. Probably including node-v12.0.0 (nughtly) is pretty enough for our needs

**Comment by dcodeIO** [comment]
Well, it doesn't say anything about what'll actually work. My local v11.8 prints pretty much the same :)

**Comment by MaxGraey** [comment]
Try `NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/ nvm i node` command

**Comment by dcodeIO** [comment]
Oh, well .. `Downloading and installing node v12.0.0-v8-canary201902266c298fffb9...`

**Comment by MaxGraey** [comment]
Yeah, it's alive)

**Comment by MaxGraey** [comment]
It seems you need rebuild tests

**Comment by dcodeIO** [comment]
10/10 would do if v8-canary would work on Windows :)

**Comment by kripken** [comment]
(yeah, I think the binary has exponent of 2, while the text format is in bytes)

**Comment by dcodeIO** [comment]
Alright, the set of instructions should be complete now, except no real docs on definitions and incomplete tests. Also fixed a few definition blurbs I came across.

**Pull request merged**
