### PR TITLE
Test pika-ci

### PR DESCRIPTION
**Pull request by dcodeIO**
This is a PR to test pika-ci as mentioned in https://github.com/AssemblyScript/assemblyscript/issues/951

### CODE REVIEW

**Comment by dcodeIO** [comment]
The initial commit won't work ofc because they run `npm run build` on their servers, which doesn't switch out `index.js`. More of a test run.

**Comment by dcodeIO** [comment]
> What we could ultimately do is to flip index.js on npm run build and reverse it on npm run clean again.

Actually, we'll most likely run into problems this way since the repo will end up with various files that should not be committed, leading to an endless story of telling everyone why their PR failed. Quite similar to what we had with dist files before.

Perhaps if there is a way to detect that the build is running inside of pika-ci we'd be able to run additional stuff on `npm run build`, but it's hard to tell whether something like that is supported since there are no docs whatsoever covering topics like this.

In general it seems that just running `npm run build` interferes with our new release magic in unfortunate ways, and a more fine-grained approach would be preferable.

**Comment by dcodeIO** [comment]
Hmm, unfortunately pika doesn't appear to run `postpublish` as well :(

**Comment by dcodeIO** [comment]
As an alternative we could make our own little pika-like thing by publishing PRs as `assemblyscript@0.8.0-pr.123-201911150131` or something. However, that might yield a quadrillion of packages being published over the course of several PRs with multiple commits to it, so I'm not sure that npm would be too keen about it.

**Comment by MaxGraey** [comment]
Hmm, probably @FredKSchott suggest something...

**Comment by enjoythelive1** [comment]
> Hmm, unfortunately pika doesn't appear to run `prepublish` as well :(

the `prepublishOnly`script only run when `npm publish` is executed. Maybe use `prepare` instead. It runs at the same time as `prepublish` use to.

**Comment by dcodeIO** [comment]
Thanks for the hint, but sadly:

> prepare: Run both BEFORE the package is packed and published, on local npm install without any arguments, and when installing git dependencies (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.

Both on local npm install and when installing git dependencies would break things.

**Comment by dcodeIO** [comment]
This PR is empty now because I merged generally useful changes to master in https://github.com/AssemblyScript/assemblyscript/pull/964.

**Pull request closed without merging**
