### PR TITLE
fix: rest parameter crash resolver

### LINKED ISSUE #2707: crash during compile
### Bug description

$ asc simple.ts -o simple.wasm

▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at Y.assert (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/std/portable/index.js:216:11)
▌     at Kn.resolveFunctionType (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/resolver.ts:395:11)
▌     at Kn.resolveType (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/resolver.ts:172:25)
▌     at Kn.resolveFunction (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/resolver.ts:2866:32)
▌     at jr.compileModuleExport (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/compiler.ts:933:48)
▌     at jr.compileModuleExports (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/compiler.ts:914:14)
▌     at jr.compile (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/compiler.ts:549:14)
▌     at Module.z0 (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/index-wasm.ts:358:32)
▌     at Module.Me (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/cli/index.js:731:31)
▌     at async file:///data/data/com.termux/files/usr/lib/node_modules/assemblyscript/bin/asc.js:33:22
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

### Steps to reproduce

`export function add(a: i32, b: i32): i32 {
  return a + b;
}

export function cache(func: (...args: any[]) => any): (...args: any[]) => any {
  return function cached(...args: any[]): any {
    return func(...args);
  }
}`

### AssemblyScript version

0.27.5

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes #2707

### CODE REVIEW

**Review by CountBleck — COMMENTED** [review]
The change in resolver.ts looks fine, but can't more functionality be tested (i.e. calling the function with 0-3 arguments)? If there are crashes from that, those should become errors.

**Comment by CountBleck** [comment]
@HerrCai0907 Try `git commit --amend --no-edit` and `git push -f` to re-run CI.

**Comment by HerrCai0907** [comment]
> calling the function with 0-3 arguments

It is invalid code in current AS. rest parameter is not supported yet.

**Review by CountBleck — COMMENTED** [review]
There should be a `func(1, 2, 3, 4)` in the test. Then, the presence of the "Not implemented: Rest parameters" error can be checked in the stderr (and the `2707.{debug,release}.wat` should be removed).

**Review by CountBleck — APPROVED** [review]

**Pull request merged**
