### PR TITLE
minor improvements for pass pipeline

### PR DESCRIPTION
**Pull request by MaxGraey**
Add more pre-SSA passes like `simplify-locals-notee-nostructure` and move `redundant set elimination` before SSA.

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by dcodeIO** [comment]
I worry a bit that we are adding so much passes to the pipeline (removing 4, adding 9, partly conditional) that optimization will become slower and slower while we keep doing this. I see that the additions reduce fixtures by about 330 lines, which is good in classical terms, and I'd lean towards merging, yet the relativistic concern remains that achieving the speed of light (zero lines of output) can only be achieved by supplying infinite energy (running passes forever) and is ultimately impossible because of diminishing returns unless becoming massless (optimizing no code at all).

Or: Where do we draw the line? How much slowdown are we willing to accept for what gain? And how can we measure this as a function of time taken vs code optimized?

**Comment by MaxGraey** [comment]
Basically this attempts also speedup pipeline by doing some work earlier, before SSA and flattering. In my internal tests it's really little bit faster than previous scheme.

> Where do we draw the line? How much slowdown are we willing to accept for what gain? And how can we measure this as a function of time taken vs code optimized?

It's will be great have some compiler benchmark ideally integrated with CI

**Comment by MaxGraey** [comment]
For `npm run test:compiler -- --create` (and via ts-node) roughly comparison: 
master: `80896 ms`
this pr: `77528 ms`

**Comment by dcodeIO** [comment]
Since this touches a lot of fixtures, can you merge master into this PR and regenerate the fixtures? Mostly just in case, i.e. if an export not present before https://github.com/AssemblyScript/assemblyscript/pull/1422 would now be present and somehow introduce a fixture-only conflict.

**Comment by MaxGraey** [comment]
Sure, done! But it seems it hasn't any changes

**Comment by dcodeIO** [comment]
Thanks!

**Pull request merged**
