### PR TITLE
[WIP] Improve Parser

### PR DESCRIPTION
**Pull request by willemneal**
Improving the parser is key to making loading of asc binaries easier.  For example, if a `wait` or `notify` instruction is used the parser can replace it with a call to an import.  Furthermore, it can allow the corresponding host code to be packaged with the binary in a custom section.  Lastly and perhaps the most exciting aspect is merging dependencies.  Ideally it should be possible to merge an arbitrary wasm binary given that its exports are a subset of the assemblyscript wasm binary's imports.

This PR, however, does not seek to replace the binaryen dependency for the compiler, but it is a first step.

### CODE REVIEW

**Comment by cdetrio** [comment]
What's the status of this? Does "merging dependencies" address https://github.com/AssemblyScript/assemblyscript/issues/194?

**Comment by willemneal** [comment]
Yes this would solve that.  I have yet to return to this in a while, but my next goal was to use Wasi to make this a portable cli tool.

**Comment by MaxGraey** [comment]
@willemneal most of changes relate to treading and its examples / tests? I guess it all outdated already. Could we close this?

**Comment by dcodeIO** [comment]
Closing this PR as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) as it appears to be outdated. I also don't quite understand what's done why and the commit log doesn't seem like it'll be possible to merge, but feel free to refine this and open a new PR.

**Pull request closed without merging**
