### PR TITLE
chore: enhance comment for extract_lane functions to include "idx" argument needs to be compile time constant

### LINKED ISSUE #2877: The docs didn't state the `v128.extract_lane`'s `idx` arg needs to compile time constant
### Bug description

as the name suggested, the docs entry for `v128.extract_lane` didn't state that the `idx` argument need to be compile time constant

### Steps to reproduce

1. try to compile this
```
let a = 0
v128.extract_lane<u8>(v128.splat<u8>(0), a)
```
2. compile error thrown

### AssemblyScript version

not sure if relevant but 0.27.30

### PR DESCRIPTION
**Pull request by KazChe**
Fixes #2877 

Changes proposed in this pull request:
⯈ Changes made in the TypeScript declaration file `std/assembly/index.d.ts`, where the v128.extract_lane functions are declared.
⯈ Comments now include: `idx argument needs to be compile time constant.` 
⯈

- [ x] I've read the contributing guidelines
- [ x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by KazChe** [comment]
hover_test

**Review by HerrCai0907 — COMMENTED** [review]
please revert change of notices.
maybe also add this comment to replace_lane

**Comment by HerrCai0907** [comment]
sorry. maybe there are some mistake, your name still need to be added in notice, but please don't change the format.

**Comment by KazChe** [comment]
> sorry. maybe there are some mistake, your name still need to be added in notice, but please don't change the format.

done, not sure how I got it all messed up the first time. Sorry about that.

**Comment by HerrCai0907** [comment]
Thanks!

**Pull request merged**
