### PR TITLE
Add LUB computation for class types

### PR DESCRIPTION
**Pull request by dcodeIO**
Addresses #2407. Previously, the LHS type was used to determine the resulting type of binary / ternary expressions. This is plausible for basic numeric types, but not so much for classes. Hence, computation of the common type now tries whether LHS and RHS map to the contextual type first, and if not (or there is none) computes the least upper bound of the two class types.

For example, in

```ts
class A {}
class B extends A {}
class C extends A {}
```

the least upper bound when mixing types `A`, `B` and or `C` is `A`, which is used if there isn't a more suitable contextual type. For example, in

```ts
class A {}
class B extends A implements I {}
class C extends A implements I {}
```

if contextual type is `I`, and `B` and `C` are mixed, the result remains `I` (both are assignable) instead of `A` (the LUB).

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by dcodeIO** [comment]
Seems to be the same breakage as previously seen in #2575. Only happens on bootstrap:release and in CI.

**Comment by dcodeIO** [comment]
Last log is interesting in that its output looks a lot like memory corruption. Something is missing, though, given that the problem cannot be reproduced locally. Things I've seen in the past were differences in line endings leading to subtly different compilation and GH actions runners running out of memory and instead of exiting showing undefined behavior.

**Comment by dcodeIO** [comment]
Looking at the bootstrapped artifact (js to wasm, step 1), it's identical to what I have locally. Narrows it down to how the artifact is invoked / used.

**Comment by dcodeIO** [comment]
In fact becomes reproducible locally when replacing `\r\n` with `\n` in all parsed files.

**Comment by dcodeIO** [comment]
Slightly better stacktrace (preserving debug info even though optimizing):

```
     abort
     at src/flow/Flow#inheritAlternatives (wasm://wasm/0032745e:wasm-function[512]:0x8d8f)
     at src/compiler/Compiler#compileSwitchStatement (wasm://wasm/0032745e:wasm-function[741]:0x1c9fd)    
     at src/compiler/Compiler#compileStatement (wasm://wasm/0032745e:wasm-function[754]:0x1eb8a)
     at src/compiler/Compiler#compileStatements (wasm://wasm/0032745e:wasm-function[755]:0x1ef2d)
     at src/compiler/Compiler#doCompileDoStatement (wasm://wasm/0032745e:wasm-function[733]:0x1b42d)      
     at src/compiler/Compiler#compileStatement (wasm://wasm/0032745e:wasm-function[754]:0x1e960)
     at src/compiler/Compiler#compileStatements (wasm://wasm/0032745e:wasm-function[755]:0x1ef2d)
     at src/compiler/Compiler#compileFunctionBody (wasm://wasm/0032745e:wasm-function[816]:0x282e9) 
```

**Comment by CountBleck** [comment]
What if you revert #2586?

**Comment by dcodeIO** [comment]
Reverted locally to check, doesn't make a difference.

**Comment by dcodeIO** [comment]
Greetings from Rtrace

```
RTRACE: Error: OOB store32 at address 106534144
    at ~lib/array/Array<i32>#__set (wasm://wasm/005ebf1a:wasm-function[1228]:0xe5e8)
    at src/flow/Flow#inheritAlternatives (wasm://wasm/005ebf1a:wasm-function[1621]:0x11bda)
```

**Comment by dcodeIO** [comment]
The first Rtrace error happens in `Compiler#compileSwitchStatement`, where `breakingFlowAlternatives` is assigned `innerFlow` and in subsequent loops `breakingFlowAlternatives.inheritAlternatives(breakingFlowAlternatives, innerFlow)` is called. Within that function, `this#flags` is assigned, which writes OOB, indicating that `breakingFlowAlternatives` points to invalid (say, already collected) memory.

Interestingly, temporarily assigning `breakingFlowAlternatives` to a global, just to keep it alive without relying on the shadow stack, mitigates the Rtrace errors, hinting towards a codegen / GC / shadow stack issue.

**Comment by dcodeIO** [comment]
Just tried with #2596, and indeed that mitigates the issue.

**Pull request merged**
