### PR TITLE
add cli exports

### PR DESCRIPTION
**Pull request by jtenner**
⯈
⯈
⯈

- [x] I've read the contributing guidelines

Hey! Just thought these might be useful for as-pect. Do you think we should add a few more?

### CODE REVIEW

**Comment by dcodeIO** [comment]
Did you try what happens when `exports` is removed? Given that there may be more exports we'd have to add, that seems like a viable alternative for the time being :)

**Comment by jtenner** [comment]
I don't know? After some testing, I discovered that adding those to the exports works just fine. Are you sure we need to remove `"exports"` altogether?

**Comment by dcodeIO** [comment]
Playing around with this currently, and apparently this already works in node 15:

```json
  "exports": {
    ".": "./index.js",
    "./cli/*": "./cli/*.js",
    "./lib/*": {
      "import": "./lib/*/index.js",
      "require": "./lib/*/umd/index.js"
    }
  },
```

**Comment by dcodeIO** [comment]
Also tried what happens when removing `exports` now, and that works with `require` as before it seems, but with `import` one has to append the `.js` file extension then.

**Comment by dcodeIO** [comment]
Another one: Appending `"./*": "./*"` as the last exports entry allows using anything within the package by means of requiring/importing its full file name.

**Comment by jtenner** [comment]
Hey. Sorry I couldn't swing around to this. I assume we are closing in favor of #1527 ?

**Pull request closed without merging**
