### PR TITLE
refactor: make `void` a unary operator

### PR DESCRIPTION
**Pull request by romdotdog**
`void`, as far as I can tell, cannot be used as an identifier, so I'm not sure why it is in `tokenIsAlsoIdentifier` 😄
The void statement is now a void unary operator.

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Comment by MaxGraey** [comment]
I guess it implement this:
```ts
void someExpr // return undefined
```
fo eample:
```ts
var a = void 0
console.log(a); // undefined
```
which is valid JS/TS syntax

**Comment by romdotdog** [comment]
This is the first PR in a series of PRs where I introduce the behavior you described here: https://github.com/AssemblyScript/assemblyscript/pull/2090#discussion_r720861292

**Comment by MaxGraey** [comment]
I see. Well I guess we could limit to support `void expr` only to functions because it may be useful. So if `expr` is not a function, just throw compiler error

**Comment by dcodeIO** [comment]
Iirc the idea here was that a `void <expr>` does not have a usable result type in AS (basically a `(drop <expr>)` of type `none`), and as such does not quality as an expression anymore but becomes a statement. Making it a unary expression instead would introduce a special case, where it is only of use if it is the child of an expression statement, then again being equivalent to a statement. Not sure if that's objectively better?

**Comment by romdotdog** [comment]
No, it is intended to be usable in these cases
```ts
let v: void = void 0;
function foo(): void {
    return void 0;
}
```

**Comment by dcodeIO** [comment]
To me this looks like on of these cases where JS/TS syntax doesn't map to AS because there's no `undefined`. For instance, I don't see how the code samples would properly translate to Wasm, i.e.

```wat
(local.set $v <?>)
```

Perhaps if there's a compelling use case, but so far this looks like more trouble than it helps.

**Comment by romdotdog** [comment]
> where JS/TS syntax doesn't map to AS because there's no `undefined`

I think simply because the TS samples typecheck is enough reason to implement this lightweight feature

> ```webassembly
> (local.set $v <?>)
> ```
The simple answer is that there wouldn't be a local at all. Declarations are just compiled down to the initializer. 

> Perhaps if there's a compelling use case

Refer to the link above that refers to @MaxGraey's comment on my last PR that was intended to address a downstream issue from this PR.

**Comment by dcodeIO** [comment]
cc @MaxGraey: What's your preference here? :)

**Comment by MaxGraey** [comment]
Well I'm ok with any decision. I guess `void expr` could be equivalent to `(drop expr)` in wasm and semantically return `void` instead `undefined` (JS-behaviour).

**Comment by romdotdog** [comment]
What is the decision?

**Comment by dcodeIO** [comment]
My primary worry is that, because there is no mapping from source to Wasm in some `void <expr>` cases, and because the special case isn't explicitly handled yet, that the change will easily lead to invalid codegen that only the validator would catch, which would be too late for proper diagnostics. A secondary consideration is that taking this risk, respectively adding complexity, just for a `void` expression that doesn't cleanly map to Wasm anyway doesn't seem worth it.

Are tests for things like `x => void something`, `return void something`, `somevar: void = void something` etc. already in place?

**Comment by dcodeIO** [comment]
> Can you give an example?

The issue would happen whenever a `void <expr>` participates as part of a more complex expression. Expressions evaluate to a value with a type, but `void <expr>` does not evaluate to a value and hence has no type. Some examples are assigning a `void <expr>` to a local or passing one as a function argument, where there is no value of any type to assign or pass. Hence this must be special-cased, so that void function parameters or locals of a void type are magically removed.

> Why doesn't it map cleanly to wasm? AFAIK it's a simple drop, right?

As long as it is used like a statement, it maps:

```js
void x;
```

```wat
(drop
 (local.get $x)
)
```

When it is part of an expression, however, it doesn't, because there is neither a value nor type to use in Wasm where in JS there would be the type/value `undefined`. What would this do, for example:

```ts
if (void x) {
  ...
}
```

The following is invalid:

```wat
(if
 (drop
  (local.get $x)
 )
 (...)
)
```

Respectively this is wrong if `x` is truthy, while `void x` would not be:

```wat
(if
 (local.get $x)
 (...)
)
```

The closest there is, to be safe if `x` is a complex expression with side-effects, would be

```wat
(drop
 (whatever-x-is)
)
```

where the `if` is eliminated statically because testing nothing for truthiness doesn't make sense.

**Comment by romdotdog** [comment]
[Well, `void` types cannot be used in if statements.](https://www.typescriptlang.org/play?#code/DYUwLgBAhgXBBuB7AlgEwgXgS9AGA3AFDIBmEAFFAJQQDeAvkA)

**Comment by dcodeIO** [comment]
Interesting, so TS has a special-cased check for that, which is about what I meant AS would need as well in every single place where a `void` value would turn up unexpectedly.

Doesn't change the underlying concern, though, as there's more than just truthiness:

```ts
let a: void = void 0;
let b: void = void 0;
if (a == b) {
  // ...
}
```

**Comment by MaxGraey** [comment]
Yeah. It looks like properly handling `void expr` is too complicated now, and I'm not sure is it worth it. Probably better just decline this during parsing and print proper error

**Pull request closed without merging**
