### PR TITLE
Infer array type from first element in auto context

### PR DESCRIPTION
**Pull request by dcodeIO**
An initial implementation of inferring array literals in auto contexts from their first element, as proposed in https://github.com/AssemblyScript/assemblyscript/issues/1007. Does not yet handle `null`s.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Regarding `null`s there are two edge cases:

1. The array starts will one or multiple `null`s
2. The array has a late `null` changing its element type to nullable

**Comment by dcodeIO** [comment]
Last commit now first resolves all elements to their common type, so something like this can be inferred as well:

```ts
var arr = [1, 2, 3.0]; // f64[]
```

```ts
var ref = new Ref();
var arr = [ref, null]; // (Ref | null)[]
```

**Comment by MaxGraey** [comment]
nice! This even better. But how more expensive this?

**Comment by dcodeIO** [comment]
It doesn't make any difference if the type is annotated, as it is the case for all of our existing code. If it isn't annotated, every element needs to be resolved, which is rather simple to do for arrays of literals, but can become costly if there are lots of non-literal elements. That's uncommon, though.

**Comment by MaxGraey** [comment]
btw I one possible optimization is check if type reached upper limit of subtypeing like we know type i32 < type i64 < type f64 (for literals). And if we reached `f64` in some places we could skip Type.commonDenominator computation and just resolve next elements as f64.

**Comment by dcodeIO** [comment]
> And if we reached f64 in some places we could skip Type.commonDenominator computation

The current currently steps up the types, so if there's an f64 at one place it will compile the next literal with an f64 context again yielding an f64. Perhaps a fast path doing nothing if `left == right` is already enough.

**Comment by MaxGraey** [comment]
Hmm, I see one disadvantage of common denominator approach. Usually when people explicitly write something like this `[2.0 as f32, 1.0, 3]` they could expect arr infer as `f32[]` instead `f64[]`. wdyt?

**Comment by dcodeIO** [comment]
I think this should produce `f32[]` already, unless it's not working? Only the first element uses contextualType=auto, but the second then uses contextualType=f32 if the first resolved to f32, so `1.0` would be interpreted as f32, as would `3`.

**Comment by MaxGraey** [comment]
Could you add test for this case?

**Comment by MaxGraey** [comment]
Found some rouge cases:
```ts
let arr1 = [null, "a"]; // should compile but error
let arr2 = [null];      // should produce error but compile
let arr3 = [1, null];   // should produce error but compile
```
https://webassembly.studio/?f=wavzyboc05

**Comment by MaxGraey** [comment]
Another potential improvement:
```ts
// nester arrays
let arr1 = [[1], [2]]; // currently produce compiler error
```

**Pull request merged**
