### PR TITLE
feat: support class member type infer

### PR DESCRIPTION
**Pull request by HerrCai0907**
Introduce new `ResolvedType` to make lazy type inference possible.

### CODE REVIEW

**Review by CountBleck — COMMENTED** [review]
It looks like the compiler requires an AST node *somewhere* because, minus the requirement in the parser, the root of this issue is [`program.ts:3995`](https://github.com/AssemblyScript/assemblyscript/blob/v0.27.17/src/program.ts#L3995) and `program.ts:4009`.

Here, stub getter/setter declarations are made with the type node from the field declaration, and the compiler has no way to obtain the initializer or its true type when the getter/setter is resolved. So some sort of hack (like this) is necessary (or a big refactor for type resolution).

By the way, does the following (using generic type parameters in initializers) work?

```ts
class Box<T> { value: T | null = null; }
class Example<T> {
    blaBlaBla = new Box<T>();
}
```

**Comment by HerrCai0907** [comment]
> So some sort of hack (like this) is necessary (or a big refactor for type resolution).

Agree. I don't want to refactor the whole type resolution at this time.

> By the way, does the following (using generic type parameters in initializers) work?

Unfortunately it doesn't work. At current time, only `Function` can contain a `contextualTypeArguments`. But It can be extend later.

**Comment by HerrCai0907** [comment]
> By the way, does the following (using generic type parameters in initializers) work?
> 
> ```ts
> class Box<T> { value: T | null = null; }
> class Example<T> {
>     blaBlaBla = new Box<T>();
> }
> ```

Not support yet.

**Comment by HerrCai0907** [comment]
This is not a good implement, it introduces new AST node, but still cannot cover all cases. I need to think about it again.

**Pull request closed without merging**
