### PR TITLE
Enable publishing

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR is what's necessary to enable publishing to npm and gpr. Unfortunately, whether this will work or not is hard to test, so I'm wondering if we should just merge it and see what happens. If anything goes wrong, we can still learn from it and update to 0.9.0 or something. Objections?

### CODE REVIEW

**Comment by MaxGraey** [comment]
probably to `0.8.1` not `0.9.0` =)

**Comment by dcodeIO** [comment]
Or that :)

**Comment by dcodeIO** [comment]
My guess so far is that npm publishing should work, but gpr fails for one of the following reasons:
* Main package is named `assemblyscript`, not `@AssemblyScript/assemblyscript`
* Loader package is named `@assemblyscript/loader`, not `@AssemblyScript/loader` or `loader` ?!
* More than just GITHUB_TOKEN must be set up to enable proper publishing

Now, as chances are that at least npm will work, I think we can give this a try.

**Comment by dcodeIO** [comment]
Will know in about half an hour :)

**Pull request merged**
