### PR TITLE
Skip full collection support if all types are acyclic

### PR DESCRIPTION
**Pull request by dcodeIO**
This is an idea recently brought up by @MaxGraey: If we know that all types within the program are inherently acyclic, we do not need to compile the parts of the GC dealing with collecting cyclic garbage.

Reduces the size of generated runtime bits by a few percent in such a scenario.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Looks like this can be improved a little more by also omitting visitor logic that is only relevant for collection, but is still compiled as part of the catch-all visitor currently.

**Comment by dcodeIO** [comment]
That looks a lot better already. There's still `appendRoot` that we don't need, and also makes me wonder whether this can be done in a better way than using builtins, like by compiling all of the GC after the main program and using a constant.

**Comment by dcodeIO** [comment]
Last commit introduces the concept of lazy library functions, which become compiled after everything else so the compiler can perform additional checks, like if everything is acyclic, before compiling them. That simplifies the implementation in this case and gets rid of a huge amount of test fixture code, but the amount of code removed is just so ridiculous that I am expecting unforeseen implications.

**Comment by dcodeIO** [comment]
Last commit targeted a few extra bytes in `decrement` but interestingly allowed to skip including RTTI in some cases.

**Comment by MaxGraey** [comment]
Great work!

**Pull request merged**
