### PR TITLE
Minor compiler improvments

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Integrated some of the improvements here into the dev branch, except those affecting the tokenizer as these should still be relatively free of conflicts - if you'd like to rebase the PR :)

**Comment by MaxGraey** [comment]
Ah, great. So I could close this?

**Comment by dcodeIO** [comment]
The tokernizer improvements aren't in the dev branch yet, but it should be possible to rebase this with just those :)

**Comment by MaxGraey** [comment]
Close. Rebased to `dev` branch in #602

**Pull request closed without merging**
